---
- name: Install fontconfig
  community.general.pacman:
    name:
      - fontconfig
      - lib32-fontconfig

- name: Check if nerd-fonts-complete is installed
  command: pacman -Q nerd-fonts-complete
  register: nerd_fonts_complete_installed
  changed_when: False

- name: Install Iosevka font
  community.general.pacman:
    # NerdFonts: Iconic font aggregator, collection, and patcher.
    name: ttf-iosevka-nerd
  become: true
  when: nerd_fonts_complete_installed.rc != 0

- name: Install siji font
  aur:
    # An iconic bitmap font based on Stlarch with additional glyphs.
    # > Used in polybar
    name: siji
    user: "{{ user.name }}"

- name: Enable sub-pixel rendering
  ansible.builtin.file:
    src: /usr/share/fontconfig/conf.avail/10-sub-pixel-rgb.conf
    dest: /etc/fonts/conf.d/10-sub-pixel-rgb.conf
    state: link
  become: true
