version: "2.1"
services:
  couchdb:
    image: couchdb
    container_name: obsidian-livesync
    environment:
      - COUCHDB_USER
      - COUCHDB_PASSWORD
    volumes:
      - ./data:/opt/couchdb/data
      - ./local.ini:/opt/couchdb/etc/local.ini
    ports:
      - 5984:5984
    restart: unless-stopped
