---
- name: As virtualbox guest, install guest additions
  become: true
  community.general.pacman:
    name:
      - virtualbox-guest-utils
  when:
    - ansible_facts['virtualization_role'] == 'guest'
    - ansible_facts['virtualization_type'] == 'virtualbox'

- name: As virtualbox guest, enable and start vboxservice
  become: true
  ansible.builtin.systemd:
    name: vboxservice.service
    enabled: true
    state: started
  when:
    - ansible_facts['virtualization_role'] == 'guest'
    - ansible_facts['virtualization_type'] == 'virtualbox'
