---
- name: Install and configure Lenovo T14
  hosts: lenovo-t14
  gather_facts: true
  handlers:
    - ansible.builtin.import_tasks: handlers/grub.yml
    - ansible.builtin.import_tasks: handlers/mkinitcpio.yml

  roles:
    - linux/system/user
    - arch/system/pacman
    - arch/system/yay
    - arch/system/chaotic-aur
    - linux/system/package-upgrade

    - machines/lenovo-t14/firmware
    - machines/lenovo-t14/video-drivers
    #- machines/lenovo-t14/screen-tearing

    - arch/system/beep
    - arch/system/fonts
    - arch/system/filesystem
    - arch/system/hibernate
    - arch/system/laptop
    - arch/system/microcode
    - arch/system/mkinitcpio
    - arch/system/networking
    - arch/system/timezone

    - linux/system/bluetooth
    - linux/system/locale
    - linux/system/ssd
    - linux/system/ssh
    #- linux/system/sshfs
    - linux/system/sound
    - linux/system/timesync

    - arch/desktop-wayland/sddm
    - arch/desktop-wayland/hyprland

    - linux/user/dev
    - linux/user/desktop
    - linux/user/docker
    - linux/user/cmdline

    #- linux/applications/atuin-client
    #- linux/applications/hacking

    - fixes/firefox_touchscreen

# TODO:
# - OpenVPN / DNS

# NOTE: Verified to run on 2024-10-28
# Manual intervention required for:
#   - Hyprland: installing of plugins and updating plugin manager
