---

- name: Install and configure Desktop Linux
  hosts: desktop-linux
  gather_facts: true
  handlers:
    - ansible.builtin.import_tasks: handlers/grub.yml
    - ansible.builtin.import_tasks: handlers/mkinitcpio.yml

  roles:
    - linux/system/user
    - arch/system/pacman
    - arch/system/yay
    - arch/system/chaotic-aur
    - linux/system/update

    - arch/system/beep
    - arch/system/bluetooth
    - arch/system/fonts
    - arch/system/filesystem
    - arch/system/hibernate
    - arch/system/locale
    - arch/system/microcode
    - arch/system/mkinitcpio
    - arch/system/networking
    - arch/system/sound
    - arch/system/timesync
    - arch/system/timezone
    - arch/system/video-drivers

    - linux/system/ssd
    - linux/system/ssh
    - linux/system/sshfs

    - arch/wayland/sddm
    - arch/wayland/hyprland

    - linux/user/cmdline
    - linux/user/dev
    - linux/user/desktop
    - linux/user/dotfiles

    - linux/common/docker
