---
- name: Install base Arch Linux system
  hosts: all
  gather_facts: true
  handlers:
    - name: Handler Grub
      ansible.builtin.import_tasks: handlers/grub.yml
    - name: Handler Mkinitcpio
      ansible.builtin.import_tasks: handlers/mkinitcpio.yml

  pre_tasks:
    - name: Validate variables
      ansible.builtin.import_tasks: roles/validate_vars.yml

  roles:
    # +- Base system setup ---------------------------------------------------+
    - { role: linux/system/user, tags: 'user' }
    - { role: arch/system/pacman, tags: 'pacman' }
    - { role: arch/system/yay, tags: 'pacman' }
    - { role: arch/system/chaotic-aur, tags: 'pacman' }
    - { role: linux/system/update, tags: 'pacman' }

    # +- Core system components ----------------------------------------------+
    - { role: arch/system/beep }
    - { role: arch/system/bluetooth, when: system.features.bluetooth }
    - { role: arch/system/fonts }
    - { role: arch/system/filesystem }
    - { role: arch/system/hibernate, when: system.swap.method != 'off' }
    - { role: arch/system/locale, locale_list: "{{ system.locale }}" }
    - { role: arch/system/microcode }
    - { role: arch/system/mkinitcpio }
    - { role: arch/system/networking }
    - { role: arch/system/security }
    - { role: arch/system/sound }
    - { role: arch/system/timesync, when: not system.is_vm_guest }
    - { role: arch/system/timezone, when: not system.is_vm_guest }

    # +- Common utilities ----------------------------------------------------+
    - { role: linux/system/ssd, tags: 'ssd' }
    - { role: linux/system/ssh }
    - { role: linux/system/sshfs, tags: 'sshfs', when: not system.is_vm_guest }

    # +- Desktop Environment -------------------------------------------------+
    - { role: arch/wayland/sddm, tags: 'DE', when: not system.is_headless }
    - { role: arch/wayland/hyprland, tags: 'DE', when: not system.is_headless }

    # +- Common user utilities -----------------------------------------------+
    - { role: linux/user/cmdline }

    # +- Machine dependent ---------------------------------------------------+
    # VirtualBox (guest)
    - { role: arch/system/virtualbox, tags: 'virtualbox' } # auto-detects if running in VirtualBox
    # Video Card Drivers (executed based on system.features.gpu)
    - { role: arch/system/video-drivers, gpu_type: "{{ system.features.gpu }}" }

    # Machine: Desktop
    - { role: machines/desktop/firmware, when: inventory_hostname == 'desktop' }
    # Machine: Lenovo-T14
    - { role: machines/lenovo-t14/firmware, when: inventory_hostname == 'lenovo-t14' }
    - { role: arch/system/laptop, when: inventory_hostname == 'lenovo-t14' }
    - { role: fixes/firefox_touchscreen, when: inventory_hostname == 'lenovo-t14' }

    # Optional / Extra
    - { role: linux/user/dev, tags: ['dev'], when: inventory_hostname == 'lenovo-t14' or inventory_hostname == 'desktop' }
    - { role: linux/common/docker, tags: ['docker'], when: inventory_hostname == 'lenovo-t14' or inventory_hostname == 'desktop' }
    - { role: linux/user/apps, tags: ['apps'], when: inventory_hostname == 'lenovo-t14' or inventory_hostname == 'desktop' }

  tasks:
    # +- Install: Terminal ---------------------------------------------------+
    - { name: Install Terminal (kitty), become: true, community.general.pacman: name=kitty, when: not system.is_vm_guest }
    - { name: Install Terminal (foot), become: true, community.general.pacman: name=foot, when: system.is_vm_guest }
