---
- name: Install and configure Lenovo T14
  hosts: lenovo-t14
  gather_facts: true
  handlers:
    - ansible.builtin.import_tasks: handlers/grub.yml

  roles:
    - linux/system/user
    - arch/system/yay
    - arch/system/chaotic-aur
    - linux/system/package-upgrade

    - arch/system/beep
    - arch/system/filesystem
    #- arch/system/hibernate
    #- arch/system/laptop
    - arch/system/man
    - arch/system/microcode
    #- arch/system/mkinitcpio
    - arch/system/networking
    - arch/system/pacman
    - arch/system/timezone

    #- linux/system/bluetooth
    - linux/system/locale
    #- linux/system/network
    #- linux/system/ssd
    - linux/system/ssh
    #- linux/system/sshfs
    - linux/system/timesync

    - machines/lenovo-t14/firmware
    #- machines/lenovo-t14/screen-tearing
    #- machines/lenovo-t14/video-drivers

    #- linux/applications/atuin-client
    #- linux/applications/cmdline
    #- linux/applications/desktop
    #- linux/applications/dev
    #- linux/applications/docker
    #- linux/applications/hacking
