# A simple playbook to install my dotfiles.
#
# This playbook assumes that bitwarden-cli is installed and available on
# localhost, and thus is meant to be run on a remote host.
#
# To use this playbook, run the following command:
#   - ansible-playbook maintenance-dotfiles.yml -l '<host>'

---
- name: Install dotfiles on a host (without bitwarden-cli)
  hosts: all
  gather_facts: true
  vars_prompt:
    - name: user_git_email
      prompt: "which email should be globally set for git?"
      private: false
  roles:
    - linux/system/package-upgrade
    - role: linux/applications/dotfiles
      vars:
        bitwarden_client_id: "{{ lookup('community.general.bitwarden', 'Bitwarden Ansible', field='client_id')[0] }}"
        bitwarden_client_secret: "{{ lookup('community.general.bitwarden', 'Bitwarden Ansible', field='client_secret')[0] }}"
        chezmoi_age_private_key: "{{ lookup('community.general.bitwarden', 'ChezMoi Dotfiles Manager', field='age_private_key')[0] }}"
        bitwarden_password: "{{ lookup('community.general.bitwarden', 'Bitwarden Ansible', field='password')[0] }}"
