---
- name: Install firmware
  notify: regenerate initramfs
  block:
    - name: Install default linux-firmware
      community.general.pacman:
        name: linux-firmware

    - name: Install aic94xx-firmware for quitlox-lenovo-t14
      aur:
        user: "{{ user.name }}"
        name: aic94xx-firmware
      when: ansible_product_name == "20UES06X00"

    - name: Install wd719x-firmware for quitlox-lenovo-t14
      aur:
        user: "{{ user.name }}"
        name: wd719x-firmware
      when: ansible_product_name == "20UES06X00"

    - name: Install extra linux-firmware (quitlox-lenovo-t14)
      community.general.pacman:
        name:
          - aic94xx-firmware
          - wd719x-firmware
          - linux-firmware-qlogic
      when: ansible_product_name == "20UES06X00"
