---
- name: Install bluez and bluez-utils packages
  pacman:
    name:
      - bluez
      - bluez-utils
    state: present
  when: ansible_virtualization_role | lower != "guest"
  when: ansible_os_family == "Archlinux"


- name: Load btusb kernel module
  modprobe:
    name: btusb
    state: present
  when: ansible_virtualization_role | lower != "guest"
  when: ansible_os_family == "Archlinux"

- name: Ensure btusb module is loaded at boot
  lineinfile:
    path: /etc/modules-load.d/btusb.conf
    line: btusb
    create: yes
  when: ansible_virtualization_role | lower != "guest"
  when: ansible_os_family == "Archlinux"

- name: Start and enable bluetooth.service
  systemd:
    name: bluetooth.service
    state: started
    enabled: true
  when: ansible_virtualization_role | lower != "guest"

- name: Install bluetooth graphical interface
  ansible.builtin.package:
    name:
      - blueman
    state: present
  when: not system.headless
