---
- name: Install sudo package and shell
  become: true
  ansible.builtin.package:
    name:
      - sudo
      - zsh
    update_cache: true

- name: Create default user
  become: true
  ansible.builtin.user:
    name: "{{ user.name }}"
    shell: "{{ user.shell }}"
    create_home: true
    move_home: false
    update_password: on_create
  notify: Notify passwd

- name: Allow members of wheel group to run sudo
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/98_wheel_allow_sudo
    state: present
    line: "%wheel ALL=(ALL:ALL) ALL"
    validate: /usr/sbin/visudo -cf %s
    create: true
    mode: "0644"

- name: Add default user to wheel group
  become: true
  ansible.builtin.user:
    name: "{{ user.name }}"
    groups: wheel
    append: true
