---
- name: Install sudo package
  become: true
  ansible.builtin.package:
    name: sudo
    update_cache: true

- name: Create default user
  become: true
  ansible.builtin.user:
    name: "{{ user_name }}"
    shell: /bin/zsh
    create_home: true
    move_home: false
    update_password: on_create
  notify: Notify passwd

# FIXME: Place file in /etc/sudoers.d/ instead
- name: Configure wheel group
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^#?\s?%wheel ALL=(ALL:ALL) ALL'
    line: "%wheel ALL=(ALL:ALL) ALL"
    validate: "/usr/sbin/visudo -cf %s"
  when: ansible_facts['os_family'] == 'Archlinux'

- name: Add default user to wheel group
  become: true
  ansible.builtin.user:
    name: "{{ user_name }}"
    groups: wheel
    append: true
  when: ansible_facts['os_family'] == 'Archlinux'
