---
- name: Install Hyprland and Friends
  community.general.pacman:
    name:
      - hyprland
      - wev
      # Required for using plugins with hyprpm
      # https://github.com/hyprwm/Hyprland/issues/4479
      - cpio
      - cmake
      - meson
      - hyprwayland-scanner
      # Dependencies
      - socat # Required for eww detecting workspace switching script
      - brightnessctl # Brightness Control
      # Libraries
      - qt5-wayland
      - qt6-wayland
      # Desktop UI
      - hyprpaper # Wallpaper
      - hyprlock # Screenlock
      - wofi # Launcher
      - eww # Widget Framework
      - swaync # Notification Daemon
      # Desktop Helpers
      - wl-clipboard # Clipboard Manager
      - udiskie # USB Automounter
      - xdg-desktop-portal-gtk # General desktop integration
      - xdg-desktop-portal-hyprland # Screensharing
      - xdg-user-dirs # User Directories
      - polkit-kde-agent # GUI Authentication
      - hyprshot # Screenshot
      # Desktop Applications (Foreground)
      - kitty # Terminal
  become: true

# TODO:
# - hyprshade: blue light filter
# - hyprgrass: touch gestures plugin
# - hycov: window switch (overview of all windows in all workspaces)
# - pyprland/monitors: generically configure monitors based on model (right-of, etc.)
# - pyprland/system_notifier: get system notifications from journal and others
# - hyprland-monitor-attached: run commands on display connect/display (for organizing workspaces)
# - hyprshot: screenshot tool
#
# - SwayOSD: On-Screen Display
# - Widget Frameworks: Ewww, Fabric, Aylur's GTK Shell
# - WayBar: Status Bar
# - SwayNotificationCenter: notification center configured through CSS
#
# - WebCord: Discord Replacement
#
# - TODO
#   - Mirror display

# Configure Firefox
# - Download & Extract WaveFox plugin (https://github.com/QNetITQ/WaveFox?tab=readme-ov-file)
# - Copy 'chrome' folder to ~/.mozilla/firefox/PROFILE/chrome
# - In about:config:
#   - toolkit.legacyUserProfileCustomizations.stylesheets = true
#   - userChrome.Toolbar.Transparency.High.Enabled = true
#   - userChrome.Toolbar.Transparency.Low.Enabled = true
#   - userChrome.Tabs.Option2.Enabled = true
#   - userChrome.Menu.Icons.Regular.Enabled = true
# Alternatives:
#  - ShyFox https://github.com/Naezr/ShyFox
#
# Inspiration:
# - https://www.reddit.com/r/unixporn/comments/ys4nfs/hyprland_glassmorphism/
# - https://www.reddit.com/r/unixporn/comments/ys4nfs/hyprland_glassmorphism/

# FIXME: Can only run within Hyprland
# - name: Initialize/Update Hyprland plugin manager
#   become: true
#   become_user: " {{ user.name }}"
#   ansible.builtin.command: hyprpm update
#   changed_when: true

# TODO: Abstract this into a role, only name of plugin should be needed

# - name: Check if Hyprland hy3 plugin repository is installed
#   become: true
#   become_user: "{{ user.name }}"
#   ansible.builtin.shell: hyprpm list | grep hy3
#   register: has_hy3
#   changed_when: false
#   failed_when: has_hy3.rc != 1 and has_hy3.rc != 0
#
# - name: Add Hyprland hy3 plugin repository
#   become: true
#   become_user: "{{ user.name }}"
#   ansible.builtin.shell: yes | hyprpm add https://github.com/outfoxxed/hy3
#   register: hy3
#   changed_when: hy3.rc == 0
#   when: has_hy3.rc == 1
#
# - name: Check if Hyprland hyprland-plugins repository is installed
#   become: true
#   become_user: "{{ user.name }}"
#   ansible.builtin.shell: hyprpm list | grep hyprland-plugins
#   register: has_hyprland_plugins
#   changed_when: false
#   failed_when: has_hyprland_plugins.rc != 1 and has_hyprland_plugins.rc != 0
#
# - name: Add Hyprland hyprland-plugins repository
#   become: true
#   become_user: "{{ user.name }}"
#   ansible.builtin.shell: yes | hyprpm add https://github.com/hyprwm/hyprland-plugins
#   register: hyprland_plugins
#   changed_when: hyprland_plugins.rc == 0
#   when: has_hyprland_plugins.rc == 1
