[".local/share/vim/bundle/repos/github.com/Shougo/dein.vim"]
	type = "archive"
	url = "https://github.com/Shougo/dein.vim/archive/master.tar.gz"
	exact = true
	stripComponents = 1
	refreshPeriod = "672h"
