#!/bin/sh

########################################
### Application Defaults
########################################

export QT_QPA_PLATFORMTHEME="qt5ct"
export EDITOR=/usr/bin/vim
export BROWSER=/usr/bin/firefox
export TERMINAL_CMD="kitty -e"
export TERMINAL="kitty"

########################################
### Configurations
########################################

# Add go to PATH
export PATH="$PATH:$HOME/go/bin"
export PATH="$PATH:$HOME/.local/bin"
# Add npm to PATH
export PATH="$PATH:$HOME/.local/share/npm/bin"

# Load XDG_BASE_DIR configuration
source ~/.config/user-dirs.dirs

# Required by ssh-agent.service, which auto-starts ssh-agent
# https://wiki.archlinux.org/index.php/SSH_keys#Start_ssh-agent_with_systemd_user
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"

########################################
### XDG_BASE_DIR: fucking conform
########################################

# Misc: Config
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc-2.0"
export VIMINIT="source $XDG_CONFIG_HOME/vim/vimrc"
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java
export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/npmrc
export DOT_SAGE="$XDG_CONFIG_HOME"/sage
# Misc: Data
export NODE_REPL_HISTORY="$XDG_DATA_HOME/node_repl_history"
export GRADLE_USER_HOME="$XDG_DATA_HOME/gradle"
export SSB_HOME="$XDG_DATA_HOME/zoom" # Zoom
# Misc: Cache
export PKG_CACHE_PATH="$XDG_CACHE_HOME/pkg-cache"

# Less
mkdir -p "$XDG_CACHE_HOME/less"
export LESSKEY="$XDG_CONFIG_HOME/less/lesskey"
export LESSHISTFILE="$XDG_CACHE_HOME/less/history"

# Python
export PYTHONSTARTUP="$XDG_CONFIG_HOME/pythonrc"
export PYTHONHISTFILE="$XDG_DATA_HOME/python_history"
export IPYTHONDIR="$XDG_CONFIG_HOME/jupyter"
export JUPYTER_CONFIG_DIR="$XDG_CONFIG_HOME/jupyter"

# Rust
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
