---
- name: Install go
  ansible.builtin.package:
    name: go

- name: Install javascript development tools
  ansible.builtin.package:
    name: nodejs npm

- name: Install java development tools
  community.general.pacman:
    name:
      - jre11-openjdk
      - jdk11-openjdk
      - openjdk11-doc
      - openjdk11-src
      - jre8-openjdk
      - jdk8-openjdk
      - openjdk8-doc
      - openjdk8-src

- name: Install python development tools
  community.general.pacman:
    name:
      - python-pip
      - python-pipx
      - python-virtualenv
      - python-wheel

- name: Install Rust
  block:
    - name: "Rust: Check if installed"
      ansible.builtin.shell: command -v cargo
      register: cargo_exists
      ignore_errors: true
    - name: "Rust: Download Installer"
      when: cargo_exists is failed
      ansible.builtin.get_url:
        url: https://sh.rustup.rs
        dest: /tmp/sh.rustup.rs
        mode: "0755"
        force: "yes"
      tags:
        - rust
    - name: "Rust: Run install script"
      when: cargo_exists is failed
      ansible.builtin.shell: /tmp/sh.rustup.rs -y
      tags:
        - rust
