---
- name: Install java development tools
  become: true
  community.general.pacman:
    name:
      - jdk11-openjdk
      - openjdk11-doc
      - openjdk11-src
      - jdk8-openjdk
      - openjdk8-doc
      - openjdk8-src
  when: install_java

- name: Install python development tools
  become: true
  community.general.pacman:
    name:
      - python-pip
      - python-pipx
      - python-virtualenv
      - python-wheel
  when: install_python
  tags: python

- name: Install Rust
  when: install_rust
  tags: rust
  block:
    - name: "Rust: Check if installed"
      ansible.builtin.command: command -v cargo
      register: cargo_exists
      ignore_errors: true
      check_mode: false
      changed_when: false
    - name: "Rust: Download Installer"
      ansible.builtin.get_url:
        url: https://sh.rustup.rs
        dest: /tmp/sh.rustup.rs
        mode: "0755"
        force: "yes"
      when: cargo_exists is failed
    - name: "Rust: Run install script"
      ansible.builtin.command: /tmp/sh.rustup.rs -y
      when: cargo_exists is failed
      changed_when: true
      become_user: " {{ user_name }}"
      become: true

- name: Install tools for development
  ansible.builtin.package:
    name:
      - lazygit
  become: true
  when: install_lsps
  tags: lsps

- name: Install formatters and linters
  ansible.builtin.package:
    name:
      - shfmt
      - taplo-cli
      - stylua
      - ansible-lint
  become: true

- name: Install formatters and linters (AUR)
  kewlfft.aur.aur:
    name:
      - prettierd
  become: true
  become_user: aur_builder

- name: Install language servers for development
  ansible.builtin.package:
    name:
      - ansible-language-server
      - bash-language-server
      - lua-language-server
      - typescript-language-server
      - vscode-json-languageserver
      - vscode-css-languageserver
      - yaml-language-server
  become: true
  when: install_lsps
  tags: lsps
# TODO: https://github.com/fubarhouse/ansible-role-golang
# Include installation of go pacakages:
#   - hyprls # language server for hypr
