---
- name: Install packages on Debian-based systems
  ansible.builtin.apt:
    name: "{{ common_packages }}"
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Install packages on Arch-based systems
  community.general.pacman:
    name: "{{ common_packages }}"
    state: present
  when: ansible_os_family == "Archlinux"

