---
- name: Install dependencies for yay AUR helper
  community.general.pacman:
    name:
      - fakeroot
      - debugedit
      - base-devel
    update_cache: true
  become: true

- name: Create the `aur_builder` user
  become: true
  ansible.builtin.user:
    name: aur_builder
    create_home: true
    group: wheel
    system: true
    shell: /bin/bash

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: true
  ansible.builtin.lineinfile:
    # NOTE: 11_aur_builder must be after 01_wheel_allow_sudo, otherwise 01_wheel_allow_sudo will take precedence
    path: /etc/sudoers.d/11_aur_builder
    line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    create: true
    mode: "0644"
    validate: "visudo -cf %s"

- name: Install yay AUR helper
  kewlfft.aur.aur:
    name: yay
  become: true
  become_user: aur_builder
