---
- name: Install sudo package
  become: true
  ansible.builtin.package:
    name: sudo

- name: Create default user
  become: true
  ansible.builtin.user:
    name: "{{ user_name }}"
    shell: /bin/zsh
    create_home: true
    update_password: on_create
  notify: Notify passwd

- name: Add wheel group
  become: true
  ansible.builtin.group:
    name: wheel
    system: true
  when: ansible_facts['os_family'] == 'Archlinux'

- name: Configure wheel group
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    state: present
    line: "%wheel ALL=(ALL) NOPASSWD:ALL"
    validate: "/usr/sbin/visudo -cf %s"
  when: ansible_facts['os_family'] == 'Archlinux'

- name: Add default user to wheel group
  become: true
  ansible.builtin.user:
    name: "{{ user_name }}"
    groups: wheel
    append: true
  when: ansible_facts['os_family'] == 'Archlinux'
