---
# - name: Install base-devel
#   community.general.pacman:
#     name: base-devel
#
# - name: Clone yay repository
#   ansible.builtin.git:
#     repo: https://github.com/Jguer/yay
#     dest: /usr/local/src/yay
#     accept_hostkey: yes
#     update: yes

- name: Install yay
  aur:
    name: yay
    user: {{ user.name }}
