---
- name: Install command-line tools
  become: true
  ansible.builtin.package:
    name:
      - zsh
      - git
      - exa
      - bat
      - fzf
      - tree
      - unzip
      # Used by zinit
      - ruby-rubygems
      - make

- name: Install command-line programs
  become: true
  community.general.pacman:
    name:
      - fd
      - btop
      - ascii
      # GitHub's official command line tool
      - github-cli
      # Alternative for default 'diff'
      # > Used by  ~/.config/zsh/zsh-config alias for 'diff'
      - colordiff
      # Ripgrep recursively searches directories for a regex pattern while respecting your gitignore.
      # For telescope Live Grep.
      - ripgrep
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install command-line programs
  ansible.builtin.apt:
    name:
      - fd-find
      - vim
      - ascii
      # Alternative for default 'diff'
      # > Used by  ~/.config/zsh/zsh-config alias for 'diff'
      - colordiff
      # Ripgrep recursively searches directories for a regex pattern while respecting your gitignore.
      # For telescope Live Grep.
      - ripgrep
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: Configure Vim
  become: true
  block:
    - name: Uninstall vim
      ansible.builtin.package:
        name: vim
        state: absent
    - name: Install gvim as default vim
      ansible.builtin.package:
        name: gvim
  when: ansible_facts['os_family'] == "Archlinux"

- name: Configure NeoVim
  block:
    - name: Install NeoVim
      become: true
      ansible.builtin.package:
        name: neovim

    - name: Install dependencies
      ansible.builtin.apt:
        name:
          - neovim
          # > Used by: Telescope Neovim plugin
          - sqlite3
          - watchman
      become: true
      when: ansible_facts['os_family'] == "Debian"

    - name: Install dependencies
      community.general.pacman:
        name:
          - neovim
          - neovim-remote
          - python-pynvim
          # > Used by: Telescope Neovim plugin
          - sqlite
      become: true
      when: ansible_facts['os_family'] == "Archlinux"

    - name: Install dependencies
      aur:
        # > Used by: vim typescript language server
        name: watchman-bin
        user: "{{ user.name }}"
      become: true
      when: ansible_facts['os_family'] == "Archlinux"

    - name: Install VSCode codicons
      aur:
        name: vscode-codicons-git
        user: "{{ user.name }}"
      become: true
      when: ansible_facts['os_family'] == "Archlinux"
