#!/bin/sh

battery_path="/sys/class/power_supply/BAT0/"
capacity=$(cat "${battery_path}capacity")
status=$(cat "${battery_path}status")

get_charging_status() {
	if [ "${status}" = "Charging" ]; then
		echo 1
	else
		echo 0
	fi
}

get_battery_icon() {
	local icon
	if [ "${status}" = "Charging" ]; then
		case $capacity in
		100) icon="󰂅" ;;    # 100%
		9[6-9]) icon="󰂅" ;; # 96-99%
		9[0-5]) icon="󰂋" ;; # 90-95%
		8[0-9]) icon="󰂊" ;; # 80-89%
		7[0-9]) icon="󰢞" ;; # 70-79%
		6[0-9]) icon="󰂉" ;; # 60-69%
		5[0-9]) icon="󰢝" ;; # 50-59%
		4[0-9]) icon="󰂈" ;; # 40-49%
		3[0-9]) icon="󰂇" ;; # 30-39%
		2[0-9]) icon="󰂆" ;; # 20-29%
		1[0-9]) icon="󰢜" ;; # 10-19%
		*) icon="󰢟" ;;      # 0-9%
		esac
	else
		case $capacity in
		100) icon="󰁹" ;;    # 100%
		9[6-9]) icon="󰁹" ;; # 96-99%
		9[0-5]) icon="󰂂" ;; # 90-95%
		8[0-9]) icon="󰂁" ;; # 80-89%
		7[0-9]) icon="󰂀" ;; # 70-79%
		6[0-9]) icon="󰁿" ;; # 60-69%
		5[0-9]) icon="󰁾" ;; # 50-59%
		4[0-9]) icon="󰁽" ;; # 40-49%
		3[0-9]) icon="󰁼" ;; # 30-39%
		2[0-9]) icon="󰁻" ;; # 20-29%
		1[0-9])
			icon="󰁺"
			notify-send -u critical "Battery Low" "Connect Charger"
			;;
		[1-9])
			icon="󰂎"
			notify-send -u critical "Battery Low" "Connect Charger"
			;;
		*) icon="󰂎" ;; # Others, assuming extreme low battery
		esac
	fi
	echo "${icon}"
}

print_battery_percentage() {
	echo "${capacity}"
}

case "$1" in
"charging") get_charging_status ;;
"icon") get_battery_icon ;;
"percent") print_battery_percentage ;;
*) exit 1 ;;
esac

exit 0
