---
- name: Check kernel version
  ansible.builtin.command:
    cmd: uname -r
  register: kernel_version
  check_mode: false

- name: Uninstall wrong virtualbox module
  community.general.pacman:
    name: virtualbox-host-modules-arch
    state: absent
  when: "'-lts' in kernel_version.stdout"

- name: Install virtualbox
  community.general.pacman:
    name:
      - virtualbox
      - virtualbox-host-dkms
      - virtualbox-guest-iso
  when: "'-lts' in kernel_version.stdout"

- name: Load kernel modules
  block:
    - name: Load kernel module vboxdrv
      ansible.builtin.modprobe:
        name: vboxdrv
        state: present
    - name: Load kernel module vboxnetadp
      ansible.builtin.modprobe:
        name: vboxnetadp
        state: present
    - name: Load kernel module vboxnetflt
      ansible.builtin.modprobe:
        name: vboxnetflt
        state: present

- name: Uninstall wrong virtualbox module
  community.general.pacman:
    name: virtualbox-host-dkms
    state: absent
  when: "'-lts' not in kernel_version.stdout"

- name: Install virtualbox
  community.general.pacman:
    name: virtualbox virtualbox-host-modules-arch virtualbox-guest-iso
  when: "'-lts' not in kernel_version.stdout"

- name: Install oracle extension pack
  become: true
  become_user: "{{ user.name }}"
  kewlfft.aur.aur:
    name: virtualbox-ext-oracle

- name: Add user to vboxusers group
  ansible.builtin.user:
    name: "{{ user.name }}"
    groups: vboxusers
    append: true
  become: true
