---
- name: Create XDG Home directories
  ansible.builtin.file:
    path: /home/{{ user.name }}/{{ item }}
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
  with_items:
    - .local/src
    - .local/bin

- name: Install 7zip
  become: true
  community.general.pacman:
    name: p7zip
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install 7zip
  become: true
  ansible.builtin.apt:
    name: p7zip-full
  when: ansible_facts['os_family'] == "Debian"

- name: Install bitwarden-cli
  become: true
  community.general.pacman:
    name: bitwarden-cli
  when: ansible_facts['os_family'] == "Archlinux"

- name: Download bitwarden-cli
  ansible.builtin.get_url:
    url: https://vault.bitwarden.com/download/?app=cli&platform=linux
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    dest: /tmp/bw.zip
  when: ansible_facts['os_family'] != "Archlinux"

- name: Unpack bitwarden-cli
  ansible.builtin.unarchive:
    remote_src: true
    src: /tmp/bw.zip
    dest: /home/{{ user.name }}/.local/bin/
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0755
  when: ansible_facts['os_family'] != "Archlinux"

- name: Check if logged into bitwarden
  ansible.builtin.command: bw login --apikey --check
  register: bitwarden_status
  environment:
    BW_CLIENTID: "{{ bitwarden.client_id }}"
    BW_CLIENTSECRET: "{{ bitwarden.client_id }}"
    PATH: "{{ ansible_env.PATH }}:/home/{{ user.name }}/.local/bin"
  become_user: "{{ user.name }}"
  become: true

- name: Login to bitwarden
  ansible.builtin.command: bw login --apikey
  environment:
    BW_CLIENTID: "{{ bitwarden.client_id }}"
    BW_CLIENTSECRET: "{{ bitwarden.client_id }}"
    PATH: "{{ ansible_env.PATH }}:/home/{{ user.name }}/.local/bin"
  when: bitwarden_status.rc != 0
  become_user: "{{ user.name }}"
  become: true

- name: Unlock bitwarden vault
  ansible.builtin.command: bw unlock {{ bitwarden.password }} --raw
  become_user: "{{ user.name }}"
  register: bitwarden_session
  environment:
    PATH: "{{ ansible_env.PATH }}:/home/{{ user.name }}/.local/bin"
  become_user: "{{ user.name }}"
  become: true

- name: Install chezmoi
  community.general.pacman:
    name: chezmoi
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install and Configure chezmoi
  block:
    - name: Initialize chezmoi
      ansible.builtin.command: "chezmoi init quitlox --promptString 'E-Mail (git)={{ git_email }}' --promptBool 'headless={{ system.headless }}'"
      environment:
        BW_SESSION: "{{ bitwarden_session.stdout }}"
        PATH: "{{ ansible_env.PATH }}:/home/{{ user.name }}/.local/bin"
      become_user: "{{ user.name }}"
      become: true

    - name: Place the age encryption key
      ansible.builtin.copy:
        content: "{{ chezmoi.age_private_key }}"
        dest: "/home/{{ user.name }}/.ssh/.age_private_key.txt"
        decrypt: true
        owner: "{{ user.name }}"
        group: "{{ user.name }}"
        mode: 0644

    - name: Be sure to run `chezmoi apply` if needed
      debug:
        msg: Be sure to run `chezmoi apply` if needed
