---
- name: Create XDG Home directories
  ansible.builtin.file:
    path: /home/{{ user.name }}/{{ item }}
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
  with_items:
    - .local/src
    - .local/bin

- name: Install 7zip
  become: true
  community.general.pacman:
    name: p7zip
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install 7zip
  become: true
  ansible.builtin.apt:
    name: p7zip-full
  when: ansible_facts['os_family'] == "Debian"

- name: Install bitwarden-cli
  become: true
  community.general.pacman:
    name: bitwarden-cli

- name: Download bitwarden-cli
  ansible.builtin.get_url:
    url: https://vault.bitwarden.com/download/?app=cli&platform=linux
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    dest: /tmp/bw.zip
  when: ansible_facts['os_family'] != "Archlinux"

- name: Unpack bitwarden-cli
  ansible.builtin.unarchive:
    src: /tmp/bw.zip
    dest: /home/{{ user.name }}/.local/bin/
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0755
  when: ansible_facts['os_family'] != "Archlinux"

- name: Check if logged into bitwarden
  ansible.builtin.command: bw login --apikey --check
  register: bitwarden_status
  environment:
    BW_CLIENTID: "{{ bitwarden.client_id }}"
    BW_CLIENTSECRET: "{{ bitwarden.client_id }}"
- name: Login to bitwarden
  ansible.builtin.command: bw login --apikey
  environment:
    BW_CLIENTID: "{{ bitwarden.client_id }}"
    BW_CLIENTSECRET: "{{ bitwarden.client_id }}"
  when: bitwarden_status.rc != 0

- name: Unlock bitwarden vault
  ansible.builtin.command: bw unlock {{ bitwarden.password }} --raw
  become_user: "{{ user.name }}"
  register: bitwarden_session

- name: Install chezmoi
  ansible.builtin.package:
    name: chezmoi

- name: Check if chezmoi configured
  ansible.builtin.stat:
    path: /home/{{ user.name }}/.local/share/chezmoi/.chezmoi.toml.tmpl
  register: dotfiles_present

- name: Install and Configure chezmoi
  block:
    - name: Initialize chezmoi
      ansible.builtin.command: chezmoi init quitlox --ssh
      become_user: "{{ user.name }}"

    - name: Place the age encryption key
      ansible.builtin.copy:
        content: "{{ chezmoi.age_public_key }}"
        dest: "/home/{{ user.name }}/.local/share/chezmoi/private_dot_ssh/.chezmoi_encryption_key.txt"
        decrypt: true
        owner: "{{ user.name }}"
        group: "{{ user.name }}"
        mode: 644

    - name: Be sure to run `chezmoi apply` if needed
      debug:
        msg: Be sure to run `chezmoi apply` if needed

  environment:
    BW_SESSION: "{{ bitwarden_session.stdout }}"

  when: dotfiles_present.stat.exists
