---
- name: Install 7zip
  community.general.pacman:
    name: p7zip
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install 7zip
  ansible.builtin.apt:
    name: p7zip-full
  when: ansible_facts['os_family'] == "Debian"

- name: Install age
  ansible.builtin.package:
    name: age

- name: Install bitwarden-cli
  community.general.pacman:
    name: bitwarden-cli

- name: Download bitwarden-cli
  ansible.builtin.get_url:
    url: https://vault.bitwarden.com/download/?app=cli&platform=linux
    owner: { { user.name } }
    group: { { user.name } }
    dest: /tmp/bw.zip
  when: ansible_facts['os_family'] != "Archlinux"

- name: Unpack bitwarden-cli
  ansible.builtin.unarchive:
    src: /tmp/bw.zip
    dest: /home/{{ user.name }}/.local/bin/
    owner: { { user.name } }
    group: { { user.name } }
    mode: 0755
  when: ansible_facts['os_family'] != "Archlinux"

- name: Create XDG Home directories
  ansible.builtin.file:
    path: /home/{{ user.name }}/{{ item }}
    state: directory
    owner: { { user.name } }
    group: { { user.name } }
  with_items:
    - .local/src
    - .local/bin

- name: Install chezmoi
  ansible.builtin.package:
    name: chezmoi

- name: Check if chezmoi configured
  ansible.builtin.stat:
    path: /home/{{ user.name }}/.local/share/chezmoi/.chezmoi.toml.tmpl
  register: dotfiles_present

- name: Configure chezmoi
  block:
    - name: Initialize chezmoi
      ansible.builtin.command: chezmoi init quitlox --ssh

    - name: Retrieve the age encryption_key from bitwarden
      ansible.builtin.set_fact:
        private_key_content: "{{ lookup('bitwarden', 'chezmoi_encryption_key.txt', itemid='b33b9474-c3ba-4961-abef-ade1010e1597', attachments=true, output='/home/{{ user.name }}/.ssh/.chezmoi_encryption_key.txt') }}"

    - name: Apply chezmoi
      ansible.builtin.command: chezmoi apply

  when: dotfiles_present.stat.exists and dotfiles_present.stat.isfile
