---
- name: Install Hyprland and Friends
  become: true
  ansible.builtin.package:
    name:
      - hyprland
      - wev
      # Required for using plugins with hyprpm
      # https://github.com/hyprwm/Hyprland/issues/4479
      - cpio
      - hyprwayland-scanner
      # Libraries
      - qt5-wayland
      - qt6-wayland
      # Desktop Applications (Background)
      - hyprpaper # Wallpaper
      - xdg-desktop-portal-hyprland # Screensharing
      - xdg-desktop-portal-gtk # Needed for file picker?
      - copyq # Clipboard Manager
      - udiskie # USB Automounter
      # Desktop Applications (Foreground)
      - wofi # Launcher

- name: Install Hyprland and Friends
  become: true
  kewlfft.aur: overskride # Bluetooth UI

  # The recommendation is the KDE Authentication Agent,
  # on Arch packaged as polkit-kde-agent
- name: Install Authentication Agent on Arch
  become: true
  ansible.builtin.package:
    name: polkit-kde-agent

# TODO:
# - hyprshade: blue light filter
# - hyprgrass: touch gestures plugin
# - hycov: window switch (overview of all windows in all workspaces)
# - pyprland/monitors: generically configure monitors based on model (right-of, etc.)
# - pyprland/system_notifier: get system notifications from journal and others
# - hyprland-monitor-attached: run commands on display connect/display (for organizing workspaces)
# - hyprshot: screenshot tool
#
# - SwayOSD: On-Screen Display
# - Widget Frameworks: Ewww, Fabric, Aylur's GTK Shell
# - WayBar: Status Bar
# - SwayNotificationCenter: notification center configured through CSS
#
# - WebCord: Discord Replacement
#
# - TODO
#   - Mirror display
#   - Display Manager

# Configure Firefox
# - Download & Extract WaveFox plugin (https://github.com/QNetITQ/WaveFox?tab=readme-ov-file)
# - Copy 'chrome' folder to ~/.mozilla/firefox/PROFILE/chrome
# - In about:config:
#   - toolkit.legacyUserProfileCustomizations.stylesheets = true
#   - userChrome.Toolbar.Transparency.High.Enabled = true
#   - userChrome.Toolbar.Transparency.Low.Enabled = true
#   - userChrome.Tabs.Option2.Enabled = true
#   - userChrome.Menu.Icons.Regular.Enabled = true
# Alternatives:
#  - ShyFox https://github.com/Naezr/ShyFox
#
# Inspiration:
# - https://www.reddit.com/r/unixporn/comments/ys4nfs/hyprland_glassmorphism/
# - https://www.reddit.com/r/unixporn/comments/ys4nfs/hyprland_glassmorphism/

- name: Initialize/Update Hyprland plugin manager
  become: true
  become_user: " {{ user_name }}"
  ansible.builtin.command: hyprpm update
  changed_when: true

# TODO: Abstract this into a role, only name of plugin should be needed

- name: Check if Hyprland hy3 plugin repository is installed
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.command: hyprpm list | grep hy3
  result: hy3
  changed_when: false

- name: Add Hyprland hy3 plugin repository
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.command: hyprpm add https://github.com/outfoxxed/hy3
  changed_when: hy3.rc == 0
  when: hy3.rc == 0

- name: Check if Hyprland hyprland-plugins repository is installed
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.command: hyprpm list | grep hyprland-plugins
  result: hyprland-plugins
  changed_when: false

- name: Add Hyprland hyprland-plugins repository
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.command: hyprpm add https://github.com/hyprwm/hyprland-plugins
  changed_when: hy3.rc == 0
  when: hyprland-plugins.rc == 0
