---
- name: Install command-line programs and dependencies
  become: true
  ansible.builtin.package:
    name:
      # Bare Essentials
      - zsh
      - starship
      - git
      # Frequently used tools
      - exa
      - bat
      - fzf
      # Programs
      - tree
      - unzip
      - make
      - btop
      - ascii # Manpage with ASCII table
      # Help / Man
      - man-db
      - man-pages
      - texinfo

      # Dependencies
      # Ripgrep recursively searches directories for a regex pattern while respecting your gitignore.
      # > Used by Neovim Telescope Live Grep.
      - ripgrep
      # Alternative for default 'diff'
      # > Used by  ~/.config/zsh/zsh-config alias for 'diff'
      - colordiff

- name: Install command-line programs and dependencies on Arch
  become: true
  community.general.pacman:
    name:
      - fd
      # Package Manager for the Ruby Language
      # > Used by: zinit
      - rubygems
      # Simple database
      # > Used by: Neovim Telescope
      - sqlite
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install command-line programs and dependencies on Debian
  become: true
  ansible.builtin.apt:
    name:
      - fd-find
      # Package Manager for the Ruby Language
      # > Used by: zinit
      - ruby-rubygems
      # Simple database
      # > Used by: Neovim Telescope
      - sqlite3
  when: ansible_facts['os_family'] == "Debian"

- name: Install vim distribution on Arch
  become: true
  when: ansible_facts['os_family'] == "Archlinux"
  block:
    - name: Uninstall vim
      ansible.builtin.package:
        name: vim
        state: absent
      become: true
    - name: Install gvim as default vim
      ansible.builtin.package:
        name: gvim
      become: true

- name: Install neovim and dependencies
  block:
    - name: Install NeoVim and dependencies
      community.general.pacman:
        name:
          - neovim
          # Dependencies of plugins
          - imagemagick # Required for image.nvim
          - github-cli # Required for octo.nvim
          - glab # Required for gitlab.nvim ?
          # Dependencies of rocks.nvim
          - luajit
          - luarocks
          # Python client for Neovim for plugins written in Python
          - python-pynvim
      become: true
      when: ansible_facts['os_family'] == "Archlinux"

    - name: Install NeoVim and dependencies (AUR)
      kewlfft.aur.aur:
        name:
          - vivify # Required for vivify.nvim
      become: true
      become_user: aur_builder

    - name: Install NeoVim on Debian
      community.general.snap:
        name:
          - nvim
        classic: true
      become: true
      when: ansible_facts['os_family'] == "Debian"

    - name: Install pynvim on Debian
      ansible.builtin.apt:
        name:
          # Python client for Neovim for plugins written in Python
          - python3-pynvim
      become: true
      when: ansible_facts['os_family'] == "Debian"

    - name: Install VSCode codicons on Arch
      kewlfft.aur.aur:
        name: vscode-codicons-git
      become: true
      become_user: aur_builder
      when: ansible_facts['os_family'] == "Archlinux"

    - name: Install VSCode codicons on Debian
      community.general.npm:
        name: "@vscode/codicons"
        global: true
      become: true
      when:
        - ansible_facts['os_family'] == "Debian"
        - "'npm' in ansible_facts.packages"
