---
- name: Install mail client
  ansible.builtin.package:
    name: thunderbird
- name: Install discord
  ansible.builtin.package:
    name: discord
- name: Install browser
  ansible.builtin.package:
    name: firefox

- name: Install qutebrowser
  block:
    - name: Install qutebrowser
      community.general.pacman:
        name: qutebrowser
    - name: Install tldextract
      aur:
        # Dependency for password managers (bitwarden)
        name: python-tldextract

- name: Install pdf application
  community.general.pacman:
    name:
      # Zathura is a highly customizable and functional document viewer.
      - zathura
      # PDF support for Zathura
      - zathura-pdf-mupdf

- name: Install obsidian
  ansible.builtin.package:
    name: obsidian

- name: Install spotify
  aur:
    name:
      - spotify
    # Command-line Spotify client written in Rust
    # - aur: spotify-tui
    # Lightweight spotify streaming daemon with spotify connect
    # support.
    # > Used by spotify-tui
    # - pacman: spotifyd

- name: Install reference manager
  aur:
    name: zotero-bin

- name: Message concerning zotero
  ansible.builtin.debug:
    msg: "Don't forget to install the zotero-better-bibtex addon"

- name: Install LaTeX distribution and dependencies
  block:
    - name: Install TexLive
      community.general.pacman:
        name:
          # A modernized, complete, self-contained TeX/LaTeX engine,
          # powered by XeTeX and TeXLive.
          # > Used by ~/.config/vim/settings/plugins/vimtex.vim
          - texlive-most
          - texlive-most-doc
          # > Needed for biblatex files
          - biber
    - name: Install dependencies
      # Pretty-Print LaTeX: A tool to reformat the output of latex
      # and friends into readable messages.
      # > Used by ~/.config/vim/settings/plugins/vimtex.vim
      aur: pplatex-git
