---
- name: Create group "docker"
  ansible.builtin.group:
    name: docker
    state: present

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ user.name }}"
    groups: docker
    append: true

- name: Install docker
  ansible.builtin.package:
    name: 
      - docker 
      - docker-compose

- name: Enable and start docker
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started
