---
- name: Install Bluetooth packages
  community.general.pacman:
    name:
      - bluez
      - bluez-utils
      - bluez-obex # Required for File Transfer
      - blueman
    state: present
  become: true

- name: Start and enable bluetooth.service
  ansible.builtin.systemd:
    name: bluetooth.service
    state: started
    enabled: true
  become: true

- name: Install Bluetooth GUI
  kewlfft.aur.aur:
    name: 
      - overskride
  become: true
  become_user: "{{ user_name }}"

- name: Add user to lp group # Required for Bluetooth Tether
  ansible.builtin.user:
    name: "{{ user_name }}"
    groups: lp
    append: true
  become: true
