---
- name: Install Iosevka font
  community.general.pacman:
    # NerdFonts: Iconic font aggregator, collection, and patcher.
    name: ttf-iosevka-nerd

- name: Install siji font
  aur:
    # An iconic bitmap font based on Stlarch with additional glyphs.
    # > Used in polybar
    name: siji

- name: Enable sub-pixel rendering
  ansible.builtin.file:
    src: /usr/share/fontconfig/conf.avail/10-sub-pixel-rgb.conf
    dest: /etc/fonts/conf.d/10-sub-pixel-rgb.conf
    state: link

