---
- name: Install microcode updates for intel
  pacman:
    name: intel-ucode
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
  notify:
    - update grub
    - update syslinux
  when: system.processor == "intel"

- name: Install microcode updates for amd
  pacman:
    name: amd-ucode
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
  notify:
    - update grub
    # TODO:
    - update syslinux
  when: system.processor == "amd"

