---
- name: Configure TRIM for SDDs
  block:
    - name: Install util-linux for SSD TRIM support
      community.general.pacman:
        name: util-linux

    - name: Enable TRIM for SSDs
      ansible.builtin.systemd:
        name: fstrim.timer
        state: started
        enabled: true
        daemon_reload: true
      become: true
      when: ansible_facts['os_family'] == "Archlinux"
