---
- name: Install java development tools
  become: true
  community.general.pacman:
    name:
      - jdk11-openjdk
      - openjdk11-doc
      - openjdk11-src
      - jdk8-openjdk
      - openjdk8-doc
      - openjdk8-src

- name: Install python development tools
  become: true
  community.general.pacman:
    name:
      - python-pip
      - python-pipx
      - python-virtualenv
      - python-wheel

- name: Install Rust
  block:
    - name: "Rust: Check if installed"
      ansible.builtin.command: command -v cargo
      register: cargo_exists
      ignore_errors: true
      check_mode: false
      changed_when: false
    - name: "Rust: Download Installer"
      when: cargo_exists is failed
      ansible.builtin.get_url:
        url: https://sh.rustup.rs
        dest: /tmp/sh.rustup.rs
        mode: "0755"
        force: "yes"
      tags:
        - rust
    - name: "Rust: Run install script"
      ansible.builtin.command: /tmp/sh.rustup.rs -y
      when: cargo_exists is failed
      changed_when: true
      tags:
        - rust
