---
- name: Configure Wireshark
  block:
    - name: Install Wireshark
      community.general.pacman:
        name: wireshark-qt
      become: true
    - name: Add user to wireshark group
      ansible.builtin.user:
        user: "{{ user_name }}"
        groups: wireshark
        append: true

- name: Install other hacking tools
  community.general.pacman:
    name:
      - nmap
      - sqlmap
