---
- name: Configure audio
  block:
    - name: Install sound base packages
      become: true
      community.general.pacman:
        name:
          - pipewire
          - lib32-pipewire
          - pipewire-docs
          - wireplumber
          - pipewire-alsa
          - pipewire-pulse
          - pipewire-audio

    - name: Install sound front-end packages
      become: true
      community.general.pacman:
        name:
          - pavucontrol
          - pamixer

    - name: Ensure pulseaudio is not installed
      become: true
      community.general.pacman:
        name:
          - pulseaudio
          - pulseaudio-bluetooth
        state: absent

- name: Configure noise supression
  notify: restart pipewire
  block:
    - name: Install required package
      community.general.pacman:
        name: noise-suppression-for-voice
      become: true
    - name: Ensure ~/.config/pipewire exists
      ansible.builtin.file:
        path: /home/{{ user_name }}/.config/pipewire/pipewire.conf.d/
        state: directory
        mode: "0755"
    - name: Copy over configuration file # TODO: Move this config to /etc
      ansible.builtin.copy:
        src: "{{ role_path }}/files/99-input-denoising.conf"
        dest: "/home/{{ user_name }}/.config/pipewire/pipewire.conf.d/99-input-denoising.conf"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: "0644"
