return {
    -- "anuvyklack/hydra.nvim",
    -- dependencies = {
    --     "chrisgrieser/nvim-spider",
    -- },
    -- config = function()
    --     local Hydra = require("hydra")
    --
    --     -- Word motion
    --     Hydra({
    --         name = "Spider",
    --         config = {
    --             color = "pink",
    --             hint = "statusline",
    --         },
    --         mode = { "n", "x", "o" },
    --         body = ",",
    --         heads = {
    --             { "w",     "<Plug>(smartword-w)" },
    --             { "b",     "<Plug>(smartword-b)" },
    --             { "e",     "<Plug>(smartword-e)" },
    --             { "ge",    "<Plug>(smartword-ge)" },
    --             { "<Esc>", nil,                   { exit = true, mode = "n" } },
    --         },
    --     })
    -- end,
}
