---
- name: Install SSH on Arch
  community.general.pacman:
    name: openssh
    update_cache: true
  become: true
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install SSH on Debian
  ansible.builtin.apt:
    name: ssh
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: Disable SSH root login
  ansible.builtin.copy:
    src: "{{ role_path }}/files/00-deny-root.conf"
    dest: /etc/ssh/sshd_config.d/00-deny-root.conf
    owner: root
    group: root
    mode: "0644"
  notify: restart ssh
  become: true

- name: Force public key authentication
  ansible.builtin.copy:
    src: "{{ role_path }}/files/00-force-public-key.conf"
    dest: /etc/ssh/sshd_config.d/00-force-public-key.conf
    owner: root
    group: root
    mode: "0644"
  notify: restart ssh
  become: true

- name: Set custom SSH port
  ansible.builtin.copy:
    src: "{{ role_path }}/files/00-custom-port.conf"
    dest: /etc/ssh/sshd_config.d/00-custom-port.conf
    owner: root
    group: root
    mode: "0644"
  notify: restart ssh
  become: true

- name: Enable and start SSH
  ansible.builtin.systemd:
    name: sshd
    enabled: true
    state: started
  become: true
