---
- name: Ensure existance of default user
  ansible.builtin.user:
    name: "{{ user.name }}"
    password: "{{ user.password | password_hash('sha512') }}"
    shell: /bin/zsh # TODO: Ensure Zsh is installed

    groups: sudo
    append: true

    create_home: true
    update_password: on_create
  when: user.name is defined

- name: Ensure sudo group has sudo privileges without password
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%sudo"
    line: "%sudo ALL=(ALL) NOPASSWD:ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: Add default user to wheel group
  ansible.builtin.user:
    user:
      name: "{{ user.name }}"
      groups: wheel
      append: true

