---
- name: Add resume hook to mkinitcpio configuration
  become: true
  ansible.builtin.lineinfile:
    insertbefore: fsck
    firstmatch: true
    line: "    resume"
    path: /etc/mkinitcpio.conf.d/my-hooks.conf
  notify: regenerate initramfs
# Note: There is also a package called uswsusp-git which provides
# userspace commands for configuring hibernation. Unfortunately,
# the ArchWiki doesn't specify the benefits and how to configure it
# with systemd.
