---
- name: Create XDG Home directories
  ansible.builtin.file:
    path: /home/{{ user_name }}/{{ item }}
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0755"
  with_items:
    - .local/src
    - .local/bin

- name: Install 7zip
  become: true
  community.general.pacman:
    name: p7zip
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install 7zip
  become: true
  ansible.builtin.apt:
    name: p7zip-full
  when: ansible_facts['os_family'] == "Debian"
