[rocks]

[plugins]
"rocks.nvim" = "2.47.5"
"rocks-git.nvim" = "2.5.10"
"rocks-config.nvim" = "3.2.0"
"rocks-lazy.nvim" = "1.2.2"
"rocks-dev.nvim" = "1.8.1"

# +----------------------------------------------------------+
# | Colorschemes                                             |
# +----------------------------------------------------------+
"catppuccin" = { git = "catppuccin/nvim", rev = "v2.0.0" }
"tokyonight.nvim" = { git = "folke/tokyonight.nvim", rev = "v4.14.1" }
"everforest-nvim" = { git = "neanias/everforest-nvim", rev = "cf08aa67fc96946a01177ae483b7631733b4b5e6" }
"gruvbox.nvim" = { git = "ellisonleao/gruvbox.nvim", rev = "2.0.0" }

# Icons and Misc
"nvim-web-devicons" = "0.100"
"tiny-devicons-auto-colors.nvim" = { git = "rachartier/tiny-devicons-auto-colors.nvim", rev = "51f548421f8a74680eff27d283c9d5ea6e8d0074" }
"mini.icons" = "0.17.0"
"mini.hipatterns" = "0.17.0"

# +----------------------------------------------------------+
# | Editor                                                   |
# +----------------------------------------------------------+

# +- Vim Built-in Enhancements ------------------------------+
"highlight-undo.nvim" = { git = "tzachar/highlight-undo.nvim", rev = "ee32e12693d70e66f954d09a504a7371d110fc27" }
"mini.misc" = "0.17.0"
"nvim-origami" = { git = "chrisgrieser/nvim-origami", rev = "67c15fd14037778644371487fc68855b530ccd7d" }
"vim-matchup" = { git = "andymass/vim-matchup", rev = "dccb2d12ef2a703d2f076b3cda36a3339449d1eb" }
"yanky.nvim" = { git = "gbprod/yanky.nvim", rev = "784188e0a7363e762e53140f39124d786aec0832" }

# +- Visual Enhancements ------------------------------------+
"indent-blankline.nvim" = "3.9.1"
"vim-illuminate" = { git = "rrethy/vim-illuminate", rev = "0d1e93684da00ab7c057410fecfc24f434698898" }

# +- Vim Motions --------------------------------------------+
"flash.nvim" = "2.1.0"
"mini.align" = "0.17.0"
"mini.ai" = "0.17.0"
"mini.extra" = "0.17.0" # only used for mini.ai text object
"mini.splitjoin" = "0.17.0"
"nvim-spider" = { git = "chrisgrieser/nvim-spider", rev = "4fdd56a4f45bca13a607632e15a6f9f8d1b1f99e" }
"nvim-surround" = "4.0.4"
"treewalker.nvim" = { git = "aaronik/treewalker.nvim", rev = "e43b1bb8e3200ca13b986c14810ab21f7d2ff0ae" }
"vim-repeat" = { git = "tpope/vim-repeat", rev = "v1.2" }

# +- Miscellenous -------------------------------------------+
"guess-indent.nvim" = { git = "NMAC427/guess-indent.nvim", rev = "84a4987ff36798c2fc1169cbaff67960aed9776f", config = true }

# +----------------------------------------------------------+
# | Integrated Development Environment                       |
# +----------------------------------------------------------+

# +- Comments / Documentation -------------------------------+
"debugprint.nvim" = { git = "andrewferrier/debugprint.nvim", rev = "v7.1.1" }

# +- Completion ---------------------------------------------+
"blink.cmp" = { git = "saghen/blink.cmp", rev = "v1.10.2" }
# +- Completion: Sources ------------------------------------+
"blink.compat" = { git = "saghen/blink.compat", rev = "v2.5.0" }
"blink-ripgrep.nvim" = { git = "mikavilpas/blink-ripgrep.nvim", rev = "v2.2.6" }
"blink-cmp-conventional-commits" = { git = "disrupted/blink-cmp-conventional-commits", rev = "28f46593ef5e03ba7525bdf6075be0c56c6ceb55" }
"blink-cmp-env" = { git = "bydlw98/blink-cmp-env", rev = "99af62c1f9aa46005e8f50ad4ccee581946546ca" }
"blink-cmp-git" = { git = "kaiser-yang/blink-cmp-git", rev = "v3.0.0" }
"cmp-bufname" = { git = "rasulomaroff/cmp-bufname", rev = "e6ea451b13ff0942232bad19ea6f2bd8929aa86c" }
"cmp-dap" = { git = "rcarriga/cmp-dap", rev = "ea92773e84c0ad3288c3bc5e452ac91559669087" }
"cmp-vimtex" = { git = "micangl/cmp-vimtex", rev = "c09ca05bfa0641754516f13294d73d3799a02fc8" }
"nvim-html-css" = { git = "jezda1337/nvim-html-css", rev = "510223bdd5533ed49cad5d8a13ec8b40ab16dcda" }
# +- Completion: Copilot-------------------------------------+
"copilot.vim" = { git = "github/copilot.vim", rev = "v1.59.0" }
"sidekick.nvim" = { git = "folke/sidekick.nvim", rev = "v2.3.0" }
# +- Completion: Extras -------------------------------------+
"colorful-menu.nvim" = { git = "xzbdmw/colorful-menu.nvim", rev = "b51a659459df8d078201aefc995db8175ed55e84" }
"luasnip" = { git = "l3mon4d3/luasnip", rev = "v2.5.0" }
"nvim-scissors" = { git = "chrisgrieser/nvim-scissors", rev = "9cc1ba06afa8b23b0d30cadc02c40940df1d701e" }

# +- Debugging ----------------------------------------------+
"nvim-dap" = { git = "mfussenegger/nvim-dap", rev = "45a69eba683a2c448dd9ecfc4de89511f0646b5f" }
"nvim-dap-ui" = { git = "rcarriga/nvim-dap-ui", rev = "1a66cabaa4a4da0be107d5eda6d57242f0fe7e49" }
"debugmaster.nvim" = { git = "miroshqa/debugmaster.nvim", rev = "505d9a269d657ce8e0fa5601e0530f0d8798038c" }
"nvim-dap-virtual-text" = { git = "theHamsta/nvim-dap-virtual-text", rev = "fbdb48c2ed45f4a8293d0d483f7730d24467ccb6", config = true }
"nvim-dap-repl-highlights" = { git = "liadoz/nvim-dap-repl-highlights", rev = "f31deba47fe3ee6ff8d2f13d9dbd06b2d1ae06b5" }
"goto-breakpoints.nvim" = { git = "ofirgall/goto-breakpoints.nvim", rev = "d14776899eda4023667b246e5c53c14a7c41f88e" }
# FIXME: remove after https://github.com/mfussenegger/nvim-dap/issues/1388
"nvim-dap-view" = { git = "igorlfs/nvim-dap-view", rev = "v1.1.1" }

# +- Git ----------------------------------------------------+
"neogit" = { git = "NeogitOrg/neogit", rev = "792c139da736230855e8341ebe6175bb6eb8268b" }
"git-conflict.nvim" = { git = "akinsho/git-conflict.nvim", rev = "v2.1.0" }
"gitsigns.nvim" = { git = "lewis6991/gitsigns.nvim", rev = "v2.1.0" }
# +- Git: Forges --------------------------------------------+
"gitlab.nvim" = { git = "harrisoncramer/gitlab.nvim", rev = "v4.1.1" }
# +- Git: Diff ----------------------------------------------+
"diffview.nvim" = { git = "dlyongemallo/diffview.nvim", rev = "v0.31" }
"diffchar.vim" = { git = "rickhowe/diffchar.vim", rev = "14fc3fc79356d6b80462df8dbc8934f293145b9a" }

# +- Language Server Protocol -------------------------------+
"fastaction.nvim" = { git = "chaitanyabsprip/fastaction.nvim", rev = "v2.0.1" }
"lensline.nvim" = { git = "oribarilan/lensline.nvim", rev = "v2.1.0" }
"lsplinks.nvim" = { git = "icholy/lsplinks.nvim", rev = "v1.0.0" }
"glance.nvim" = { git = "DNLHC/glance.nvim", rev = "bf86d8b79dce808e65fdb6e9269d0b4ed6d2eefc" }
"hover.nvim" = { git = "lewis6991/hover.nvim", rev = "e73c00da3a9c87a21d2a8ddf7ab4a39824bd5d56" }
"workspace-diagnostics.nvim" = { git = "artemave/workspace-diagnostics.nvim", rev = "0dcd7d0a6c8f6e1ddb5bb72e1412aa4c9388718f" }
"output-panel.nvim" = { git = "mhanberg/output-panel.nvim", rev = "v1.0.1" }
"overlook.nvim" = { git = "williamhsieh/overlook.nvim", rev = "6f74f20a61204275989050a2c1221bdc53b534c4" }
"garbage-day.nvim" = { git = "zeioth/garbage-day.nvim", rev = "v1.4.0" }

# +- Search -------------------------------------------------+
"grug-far.nvim" = { git = "magicduck/grug-far.nvim", rev = "1.6.68" }

# +- Session and Project Management -------------------------+
"resession.nvim" = { git = "stevearc/resession.nvim", rev = "v1.2.1" }

# +- Test ---------------------------------------------------+
"neotest" = "5.15.0"
# "quicktest.nvim" = { git = "quolpr/quicktest.nvim", rev = "de70b0a171127b6bc67d0fe4091ae2cc70ae9e11" }

# +- Tooling ------------------------------------------------+
"conform.nvim" = "9.1.0"
"nvim-lint" = { git = "mfussenegger/nvim-lint", rev = "eab58b48eb11d7745c11c505e0f3057165902461" }
"nvim-rulebook" = { git = "chrisgrieser/nvim-rulebook", rev = "083dd66b498bc142386a7c96dddab73acbf4ec20" }

# +- Treesitter ---------------------------------------------+
"nvim-treesitter" = { git = "nvim-treesitter/nvim-treesitter", rev = "4916d6592ede8c07973490d9322f187e07dfefac" }
# +- Treesitter: Pairs --------------------------------------+
"nvim-autopairs" = { git = "windwp/nvim-autopairs", rev = "59bce2eef357189c3305e25bc6dd2d138c1683f5" }
"clasp.nvim" = { git = "xzbdmw/clasp.nvim", rev = "25442429aae1b1de0627f358740613f77ec57410" }
"tabout.nvim" = { git = "abecodes/tabout.nvim", rev = "9a3499480a8e53dcaa665e2836f287e3b7764009" }
# +- Treesitter: Modules ------------------------------------+
"rainbow-delimiters.nvim" = "0.12.0"
"nvim-ts-autotag" = "scm"
"nvim-ts-context-commentstring" = "scm"
"nvim-treesitter-endwise" = { git = "RRethy/nvim-treesitter-endwise", rev = "8fe8a95630f4f2c72a87ba1927af649e0bfaa244" }
# "nvim-treesitter-textsubjects" = { git = "RRethy/nvim-treesitter-textsubjects", rev = "9e3edd38e44c8f3af5634c5e30a33ebd79227f11" }
"nvim-treesitter-textobjects" = { git = "nvim-treesitter/nvim-treesitter-textobjects", rev = "851e865342e5a4cb1ae23d31caf6e991e1c99f1e" }

# +----------------------------------------------------------+
# | Language Support                                         |
# +----------------------------------------------------------+

# +- LSP ----------------------------------------------------+
"nvim-lspconfig" = "2.8.0"
"mason.nvim" = { git = "mason-org/mason.nvim", rev = "v2.2.1" }
# "neoconf.nvim" = { git = "folke/neoconf.nvim", rev = "8afa42277fa944f60071241b37e922b6f2d9a9f8" }
"codesettings.nvim" = { git = "mrjones2014/codesettings.nvim", rev = "v1.6.7" }
"otter.nvim" = "2.14.5"

# +- Config -------------------------------------------------+
"schemastore.nvim" = { git = "b0o/SchemaStore.nvim", rev = "20d4e9970798123e6197acb1c85c4b1e897efd29" }
# +- HTTP ---------------------------------------------------+
"kulala.nvim" = { git = "mistweaverco/kulala.nvim", rev = "v5.3.4", ft = "http" }
# +- LaTeX --------------------------------------------------+
"vimtex" = { git = "lervag/vimtex", rev = "v2.17" }
# +- Lua ----------------------------------------------------+
"lazydev.nvim" = { git = "folke/lazydev.nvim", rev = "v1.10.0" }
"luvit-meta" = { git = "Bilal2453/luvit-meta", rev = "cc9b2d412d2fbd30b94a70cfc214c2a3be27a0a2" }
# +- Markdown -----------------------------------------------+
# "render-markdown.nvim" = { git = "MeanderingProgrammer/render-markdown.nvim", rev = "v8.4.0" }
"markview.nvim" = "28.2.0"
"obsidian.nvim" = "3.16.2"
"vivify.vim" = { git = "jannis-baum/vivify.vim", rev = "39663f5d201609731a2ac3de58d6cd81f1f64efe" }
"table-nvim" = { git = "scjangra/table-nvim", rev = "816d251963bf4c8c3d765dab40ebac3c259c7b6d" }
# +- Python -------------------------------------------------+
"python.nvim" = { git = "joshzcold/python.nvim", rev = "2e09bcb0a799eab6613744e802c11adea659d73d" }
"neotest-python" = { git = "nvim-neotest/neotest-python", rev = "e6df4f1892f6137f58135917db24d1655937d831" }
"nvim-dap-python" = "scm"
# +- Rust ---------------------------------------------------+
"rustaceanvim" = { git = "mrcjkb/rustaceanvim", rev = "v9.0.3" }
"krust.nvim" = { git = "alexpasmantier/krust.nvim", rev = "899b65851d25d6eb250833709ab5b27c760171dd", ft = "rust", config = true }
# +- Vim ----------------------------------------------------+
"one-small-step-for-vimkind" = { git = "jbyuki/one-small-step-for-vimkind", rev = "1af6ffb9b5229a856e8090fa2f690e0931a5aace" }
# +- Web ----------------------------------------------------+
"typescript-tools.nvim" = { git = "pmizio/typescript-tools.nvim", rev = "c2f5910074103705661e9651aa841e0d7eea9932" }
"tailwind-tools.nvim" = { git = "luckasRanarison/tailwind-tools.nvim", rev = "v0.3.2" }
# +- Minor Languages ----------------------------------------+
"chezmoi.vim" = { git = "alker0/chezmoi.vim", rev = "73b30df35c6b645ebd2e6a440eea8463ef3c3f47" }
"csvview.nvim" = { git = "hat0uma/csvview.nvim", rev = "v1.3.0" }
"nvim-ansible" = { git = "mfussenegger/nvim-ansible", rev = "c7f595d568b588942d4d0c37b5cd6cae3764a148" }
"nvim-parinfer" = "1.2.0"
"vim-sage" = { git = "petRUShka/vim-sage", rev = "4b036eead948e3ae1d414efdeefe11f7543fc366" }
"yuck.vim" = { git = "elkowar/yuck.vim", rev = "9b5e0370f70cc30383e1dabd6c215475915fe5c3" }

# +----------------------------------------------------------+
# | User Interface                                           |
# +----------------------------------------------------------+

"edgy.nvim" = "1.10.2"
"no-neck-pain.nvim" = "2.5.3"

# +- Buffer Switcher ----------------------------------------+
"dart.nvim" = { git = "iofq/dart.nvim", rev = "af7256291c8f692647004b9a9fc0e92b6084a691" }

# +- LLM ----------------------------------------------------+
"codecompanion.nvim" = { git = "olimorris/codecompanion.nvim", rev = "v19.12.0" }
"codecompanion-spinners.nvim" = { git = "lalitmee/codecompanion-spinners.nvim", rev = "v1.0.1" }
"codecompanion-history.nvim" = { git = "ravitemer/codecompanion-history.nvim", rev = "bc1b4fe06eaaf0aa2399be742e843c22f7f1652a" }
# "vectorcode" = { git = "davidyz/vectorcode", rev = "0.7.20" }
# "mcphub.nvim" = { git = "ravitemer/mcphub.nvim", rev = "f94e1c8e1aea68c3f8f6df5cf51c752033584fd0" }

# +- File Explorer ------------------------------------------+
"neo-tree.nvim" = "3.40.0"
"nvim-window-picker" = { git = "s1n7ax/nvim-window-picker", rev = "v2.4.0" }
"oil.nvim" = "2.15.0"

# +- Notifications ------------------------------------------+
"fidget.nvim" = "1.6.0"

# +- Outline ------------------------------------------------+
"aerial.nvim" = "3.1.0"
"namu.nvim" = { git = "bassamsdata/namu.nvim", rev = "v0.6.0" }

# +- Runner (Overseer) --------------------------------------+
"overseer.nvim" = { git = "stevearc/overseer.nvim", rev = "f818eefff81f4b12fb7cf236f1b6c16768a2fcbc" }

# +- Statusline ---------------------------------------------+
"lualine.nvim" = "scm"
"lualine-pretty-path" = { git = "bwpge/lualine-pretty-path", rev = "852cb06f3562bced4776a924e56a9e44d0ce634f" }
# -- Breadcrumbs
"nvim-navic" = { git = "SmiteshP/nvim-navic", rev = "f5eba192f39b453675d115351808bd51276d9de5" }
# -- Context
"nvim-treesitter-context" = { git = "nvim-treesitter/nvim-treesitter-context", rev = "b0c45cefe2c8f7b55fc46f34e563bc428ef99636" }

# +- Quickfix -----------------------------------------------+
"trouble.nvim" = { git = "folke/trouble.nvim", rev = "bd67efe408d4816e25e8491cc5ad4088e708a69a" }

# +- Miscelleneous ------------------------------------------+
"icon-picker.nvim" = "scm"
"todo-comments.nvim" = "1.5.0"
"which-key.nvim" = "3.17.0"

# +----------------------------------------------------------+
# | Miscelleneous                                            |
# +----------------------------------------------------------+

# "codesnap.nvim" = { git = "mistricky/codesnap.nvim", rev = "d8d55f5b62a6c12bc7756eb0b997a776eafd086e" }
"gitignore.nvim" = { git = "wintermute-cell/gitignore.nvim", rev = "0344f643768c4d64af4add8c1bdddf6f7d4c9010" }
"minesweeper.nvim" = { git = "Pansther/minesweeper.nvim", rev = "a368da548d71e17e4c411eb7e97e6980a0c0264a", config = true }
"neovim-tips" = { git = "saxon1964/neovim-tips", rev = "v0.8.4" }
"snacks.nvim" = { git = "folke/snacks.nvim", rev = "v2.31.0", opt = true }

# +----------------------------------------------------------+
# | Dependencies                                             |
# +----------------------------------------------------------+
"nvim-nio" = "1.10.1"  # pytest
"plenary.nvim" = { git = "nvim-lua/plenary.nvim", rev = "74b06c6c75e4eeb3108ec01852001636d85a932b" }  # codecompanion, typescript-tools.nvim, dart.nvim
"jsregexp" = "0.1.0"  # luasnip
"nui.nvim" = { git = "muniftanjim/nui.nvim", rev = "0.4.0" } # vscode-diff.nvim

# +----------------------------------------------------------+
# | Config                                                   |
# +----------------------------------------------------------+

[config]
plugins_dir = "_plugins/"
auto_setup = false

[dev]
path = "/home/quitlox/Workspace/neovim-plugins"

# +----------------------------------------------------------+
# | Graveyard                                                |
# +----------------------------------------------------------+
# "marks.nvim" = { git = "chentoast/marks.nvim" }
# "dial.nvim" = "0.4.0"

# "nvim-hlslens" = { git = "kevinhwang91/nvim-hlslens", rev = "0bd7ddb0aecf095055e9cb6eef0c25c70fb69cfc", pin = true } # pinned because of outdated release
#     hlslens causes commandline completion to dissapear: https://github.com/kevinhwang91/nvim-hlslens/issues/75

# +- Go -----------------------------------------------------+
# "go.nvim" = { version = "0.10.0", ft = ["go", "gomod"] }
# "guihua.lua" = { git = "ray-x/guihua.lua", rev = "d783191eaa75215beae0c80319fcce5e6b3beeda" } # NOTE: Overwrites fzy which may cause issues (str(fixed for now, but still)), maybe switch to use gopher instead if I ever need it
