# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Bundled configuration packages managed in dotfiles repository.
homeassistant:
  packages:
    nixos_rebuild: !include nixos_rebuild_package.yaml
    nixos_reboot: !include nixos_reboot_package.yaml

# Owned by Home Assistant for UI-based configuration.
automation: !include automations.yaml

script: !include scripts.yaml
scene: !include scenes.yaml

# Network configuration (reverse proxy)
http:
  server_port: 4002
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 192.168.1.100