---
- name: Configure audio (PipeWire)
  block:
    - name: Install sound base packages
      become: true
      community.general.pacman:
        name:
          - pipewire
          - pipewire-docs
          - lib32-pipewire
          - wireplumber
          - pipewire-audio
          - pipewire-alsa
          - pipewire-pulse
          - pavucontrol # Graphical Interface

    - name: Ensure pulseaudio is not installed
      community.general.pacman:
        name:
          - pulseaudio
          - pulseaudio-bluetooth
        state: absent
      become: true

- name: Configure noise supression
  notify: restart pipewire
  block:
    - name: Install required package
      become: true
      community.general.pacman:
        name: noise-suppression-for-voice
    - name: Ensure ~/.config/pipewire exists
      ansible.builtin.file:
        path: /home/{{ user.name }}/.config/pipewire/pipewire.conf.d/
        state: directory
        mode: "0755"
    - name: Copy over configuration file # TODO: Move this config to /etc
      ansible.builtin.copy:
        src: "{{ role_path }}/files/99-input-denoising.conf"
        dest: "/home/{{ user.name }}/.config/pipewire/pipewire.conf.d/99-input-denoising.conf"
        owner: "{{ user.name }}"
        group: "{{ user.name }}"
        mode: "0644"

- name: Configure soft-mixer to resolve USB DAC volume issue
  notify: restart pipewire
  block:
    - name: Ensure /etc/wireplumber/wireplumber.conf.d exists
      ansible.builtin.file:
        path: /etc/wireplumber/wireplumber.conf.d/
        state: directory
        mode: "0755"
      become: true

    - name: Set api.alsa.soft-mixer to true in WirePlumber configuration
      ansible.builtin.copy:
        dest: /etc/wireplumber/wireplumber.conf.d/alsa-soft-mixer.conf
        content: |
          monitor.alsa.rules = [
            {
              matches = [
                {
                  device.name = "~alsa_card.*"
                }
              ]
              actions = {
                update-props = {
                  # Do not use the hardware mixer for volume control. It
                  # will only use software volume. The mixer is still used
                  # to mute unused paths based on the selected port.
                  api.alsa.soft-mixer = true
                }
              }
            }
          ]
        owner: root
        group: root
        mode: "0644"
      become: true
