---
- name: Install video drivers for Lenovo T14
  community.general.pacman:
    name:
      - xf86-video-amdgpu
      - xf86-video-ati
      - libva-mesa-driver
      - libva-utils
      - libvdpau
  when: ansible_product_name == "20UES06X00"
