---
# https://wiki.archlinux.org/title/PC_speaker#Globally

- name: Disable computer speaker at boot
  become: true
  ansible.builtin.copy:
    src: "{{ role_path }}/files/nobeep.conf"
    dest: /etc/modprobe.d/nobeep.conf
    mode: "0440"

- name: Disable computer speaker now
  block:
    - name: Check if 'pcspkr' module is loaded
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          lsmod | grep '^pcspkr'
      register: pcspkr
      failed_when: false
      changed_when: false

    - name: Disable 'pcsprk' kernel module
      become: true
      when: pcspkr.rc == 0
      register: result
      changed_when: result.rc == 0
      ansible.builtin.command: rmmod pcspkr

    - name: Check if 'snd_pcsp' module is loaded
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          lsmod | grep '^snd_pcsp'
      register: snd_pcsp
      failed_when: false
      changed_when: false

    - name: Disable 'snd_pcsp' kernel module
      become: true
      when: snd_pcsp.rc == 0
      register: result
      changed_when: result.rc == 0
      ansible.builtin.command: rmmod snd_pcsp
