---
- name: Install Docker on Debian
  ansible.builtin.include_tasks: debian.yml
  when: ansible_facts['os_family'] == "Debian"

- name: Install Docker on Arch
  ansible.builtin.include_tasks: arch.yml
  when: ansible_facts['os_family'] == "Archlinux"

- name: Create group "docker"
  ansible.builtin.group:
    name: docker
    state: present
  become: true

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ user.name }}"
    groups: docker
    append: true
  become: true

- name: Enable and start docker
  ansible.builtin.systemd:
    name: docker.socket # faster boot-time than docker.service
    enabled: true
    state: started
  become: true

- name: Enable and start docker container
  ansible.builtin.systemd:
    name: containerd.service
    enabled: true
    state: started
  become: true
