server:
  assets-path: /app/assets

theme:
  custom-css-file: /assets/user.css

document:
  head: |
    <script src="/assets/user.js"></script>

pages:
  - $include: homelab.yml
  - $include: home.yml
