- type: monitor
  cache: 1s
  title: Applications
  sites:
    - title: OpenCode
      icon: auto-invert https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/opencode.svg
      url: https://opencode.home.quitlox.dev
      check-url: https://opencode.home.quitlox.dev/global/health
      basic-auth:
        username: ${OPENCODE_USERNAME}
        password: ${OPENCODE_PASSWORD}
    - title: Beszel
      icon: sh:beszel
      url: https://beszel.home.quitlox.dev
      check-url: https://beszel.home.quitlox.dev/api/health
    - title: Home Assistant
      icon: sh:home-assistant
      url: https://homeassistant.home.quitlox.dev
      check-url: https://homeassistant.home.quitlox.dev/
    - title: Yamtrack
      icon: sh:yamtrack
      url: https://yamtrack.home.quitlox.dev
      check-url: https://yamtrack.home.quitlox.dev/health/
    - title: Code Server
      icon: di:code-server.png
      url: https://code.home.quitlox.dev
      check-url: https://code.home.quitlox.dev/healthz
