- type: group
  widgets:
    - type: extension
      title: OpenCode Sessions
      title-url: https://opencode.home.quitlox.dev
      url: http://glance-extension-opencode:8080/sessions
      cache: 5m
      allow-potentially-dangerous-html: true
    - type: extension
      title: OpenCode Projects
      title-url: https://opencode.home.quitlox.dev
      url: http://glance-extension-opencode:8080/projects
      cache: 5m
      allow-potentially-dangerous-html: true
