# Files
IgnorePath '/var/.updated'

IgnorePath '/var/lib/.updated'
IgnorePath '/var/lib/logrotate.status'
IgnorePath '/var/lib/alsa/asound.state'
IgnorePath '/var/lib/blueman/network.state'
IgnorePath '/var/lib/colord/*.db'
IgnorePath '/var/lib/pacman-mirrors/status.json'

IgnorePath '/usr/share/glib-2.0/schemas/gschemas.compiled'
IgnorePath '/usr/share/hwdata/pci.ids*'
IgnorePath '/usr/share/info/dir'
IgnorePath '/usr/share/pacman-mirrors/mirrors.json'
IgnorePath '/usr/share/perl5/vendor_perl/XML/SAX/ParserDetails.ini'
IgnorePath '/usr/share/texmf/ls-R'
IgnorePath '/usr/share/texmf-dist/ls-R'
IgnorePath '/usr/share/vim/vimfiles/doc/tags'

# Directories
IgnorePath '/boot/*'
IgnorePath '/usr/lib/*'
IgnorePath '/usr/lib32/*'
IgnorePath '/usr/lib64/*'
IgnorePath '/srv/*'
IgnorePath '/opt/*'

#IgnorePath '/usr/lib/modules/*'
IgnorePath '/usr/share/.mono/*'
IgnorePath '/usr/share/fonts/*'
IgnorePath '/usr/share/icons/*'
IgnorePath '/usr/share/mime/*'
IgnorePath '/var/db/*'
IgnorePath '/var/lib/bluetooth/*'
IgnorePath '/var/lib/docker/*'
IgnorePath '/var/lib/pacman/*'
IgnorePath '/var/lib/lightdm/*'
IgnorePath '/var/lib/mlocate/*'
IgnorePath '/var/lib/mhwd/*'
IgnorePath '/var/lib/mysql/*'
IgnorePath '/var/lib/NetworkManager/*'
IgnorePath '/var/lib/snapd/*'
IgnorePath '/var/lib/systemd/*'
IgnorePath '/var/lib/texmf/*'
IgnorePath '/var/lib/tomcat9/*'
IgnorePath '/var/lib/upower/*'
IgnorePath '/var/log/*'
IgnorePath '/var/log/journal/*'
IgnorePath '/var/spool/*'
IgnorePath '/var/tmp/*'


# /etc directories
IgnorePath '/etc/ca-certificates/*'
IgnorePath '/etc/dconf/db/*'
IgnorePath '/etc/default/*'
IgnorePath '/etc/dunst/*'
IgnorePath '/etc/fonts/*'
IgnorePath '/etc/lvm/cache/*'
IgnorePath '/etc/mkinitcpio.d/*'
IgnorePath '/etc/pacman.d/*'
IgnorePath '/etc/pulse/*'
IgnorePath '/etc/texmf/*'
IgnorePath '/etc/tomcat9/*'
IgnorePath '/etc/ssl/certs/*'

# /etc files
IgnorePath 'desktopfs-pkgs.txt'
IgnorePath 'rootfs-pkgs.txt'
IgnorePath '/etc/.updated'
IgnorePath '/etc/adjtime'
IgnorePath '/etc/crypttab'
IgnorePath '/etc/fstab'
IgnorePath '/etc/hosts'
IgnorePath '/etc/group*'
IgnorePath '/etc/gshadow*'
IgnorePath '/etc/ld.so.cache'
IgnorePath '/etc/locale.gen'
IgnorePath '/etc/machine-id'
IgnorePath '/etc/mhwd-x86_64.conf'
IgnorePath '/etc/pacman.conf.pacnew'
IgnorePath '/etc/passwd*'
IgnorePath '/etc/resolv.conf'
IgnorePath '/etc/shadow*'
IgnorePath '/etc/shells*'
IgnorePath '/etc/sudoers.d/10-installer'

IgnorePath '/etc/docker/key.json'
IgnorePath '/etc/xml/catalog'

# glob patterns
IgnorePath '/etc/*.bak'
#IgnorePath '/usr/lib/*.cache'
#IgnorePath '/usr/lib/*/distribution.ini'

# Empty Directories
IgnorePath '/etc/openvpn'
IgnorePath '/var/lib/lightdm-data'
IgnorePath '/var/lib/colord'
IgnorePath '/var/lib/dbus'
