return {
    {
        "folke/which-key.nvim",
        optional = true,
        opts = {
            defaults = {
                d = { name = "Delete" },
                m = { name = "Mark" },
            },
        },
    },
    {
        "chentoast/marks.nvim",
        cmd = {
            "MarksToggleSigns",
            "MarksListBuf",
            "MarksListGlobal",
            "MarksListAll",
            "BookmarksList",
            "BookmarksListAll",
            --
            "MarksQFListBuf",
            "MarksQFListGlobal",
            "MarksQFListAll",
            "BookmarksQFList",
            "BookmarksQFListAll",
        },
        keys = {
            { "m",         "<Plug>(Marks-set)",              desc = "Set a named mark" },
            { "m,",        "<Plug>(Marks-setnext)",          desc = "Set the next available alphabetical mark" },
            { "m;",        "<Plug>(Marks-toggle)",           desc = "Toggle a mark at the cursor." },
            { "dm",        "<Plug>(Marks-delete)",           desc = "Delete a mark (will wait for input)" },
            { "dm-",       "<Plug>(Marks-deleteline)",       desc = "Delete the marks on the current line" },
            { "dm<space>", "<Plug>(Marks-deletebuf)",        desc = "Delete all marks in the buffer" },
            { "m:",        "<Plug>(Marks-preview)",          desc = "Preview a mark" },
            { "m]",        "<Plug>(Marks-next)",             desc = "Move to the next mark" },
            { "m[",        "<Plug>(Marks-prev)",             desc = "Move to the previous mark" },
            { "dm=",       "<Plug>(Marks-delete-bookmark)",  desc = "Deletes the bookmark under the cursor" },
            { "m}",        "<Plug>(Marks-next-bookmark)",    desc = "Moves to the next bookmark" },
            { "m{",        "<Plug>(Marks-prev-bookmark)",    desc = "Moves to the previous bookmark" },
            { "m0",        "<Plug>(Marks-set-bookmark0)",    desc = "Sets a bookmark from group" },
            { "dm0",       "<Plug>(Marks-delete-bookmark0)", desc = "Deletes all bookmarks from group" },
            { "m1",        "<Plug>(Marks-set-bookmark1)",    desc = "which_key_ignore" },
            { "dm1",       "<Plug>(Marks-delete-bookmark1)", desc = "which_key_ignore" },
            { "m2",        "<Plug>(Marks-set-bookmark2)",    desc = "which_key_ignore" },
            { "dm2",       "<Plug>(Marks-delete-bookmark2)", desc = "which_key_ignore" },
            { "m3",        "<Plug>(Marks-set-bookmark3)",    desc = "which_key_ignore" },
            { "dm3",       "<Plug>(Marks-delete-bookmark3)", desc = "which_key_ignore" },
            { "m4",        "<Plug>(Marks-set-bookmark4)",    desc = "which_key_ignore" },
            { "dm4",       "<Plug>(Marks-delete-bookmark4)", desc = "which_key_ignore" },
            { "m5",        "<Plug>(Marks-set-bookmark5)",    desc = "which_key_ignore" },
            { "dm5",       "<Plug>(Marks-delete-bookmark5)", desc = "which_key_ignore" },
            { "m6",        "<Plug>(Marks-set-bookmark6)",    desc = "which_key_ignore" },
            { "dm6",       "<Plug>(Marks-delete-bookmark6)", desc = "which_key_ignore" },
            { "m7",        "<Plug>(Marks-set-bookmark7)",    desc = "which_key_ignore" },
            { "dm7",       "<Plug>(Marks-delete-bookmark7)", desc = "which_key_ignore" },
            { "m8",        "<Plug>(Marks-set-bookmark8)",    desc = "which_key_ignore" },
            { "dm8",       "<Plug>(Marks-delete-bookmark8)", desc = "which_key_ignore" },
            { "m9",        "<Plug>(Marks-set-bookmark9)",    desc = "which_key_ignore" },
            { "dm9",       "<Plug>(Marks-delete-bookmark9)", desc = "which_key_ignore" },
            { "m}0",       "<Plug>(Marks-next-bookmark0)",   desc = "Moves to the next bookmark of of the same group" },
            { "m{0",       "<Plug>(Marks-prev-bookmark0)",   desc = "Moves to the previous bookmark of of the same group" },
            { "m}1",       "<Plug>(Marks-next-bookmark1)",   desc = "Moves to the next bookmark of of the same group" },
            { "m{1",       "<Plug>(Marks-prev-bookmark1)",   desc = "Moves to the previous bookmark of of the same group" },
            { "m}2",       "<Plug>(Marks-next-bookmark2)",   desc = "Moves to the next bookmark of of the same group" },
            { "m{2",       "<Plug>(Marks-prev-bookmark2)",   desc = "Moves to the previous bookmark of of the same group" },
            { "m}3",       "<Plug>(Marks-next-bookmark3)",   desc = "Moves to the next bookmark of of the same group" },
            { "m{3",       "<Plug>(Marks-prev-bookmark3)",   desc = "Moves to the previous bookmark of of the same group" },
            { "m}4",       "<Plug>(Marks-next-bookmark4)",   desc = "Moves to the next bookmark of of the same group" },
            { "m{4",       "<Plug>(Marks-prev-bookmark4)",   desc = "Moves to the previous bookmark of of the same group" },
            { "m}5",       "<Plug>(Marks-next-bookmark5)",   desc = "Moves to the next bookmark of of the same group" },
            { "m{5",       "<Plug>(Marks-prev-bookmark5)",   desc = "Moves to the previous bookmark of of the same group" },
            { "m}6",       "<Plug>(Marks-next-bookmark6)",   desc = "Moves to the next bookmark of of the same group" },
            { "m{6",       "<Plug>(Marks-prev-bookmark6)",   desc = "Moves to the previous bookmark of of the same group" },
            { "m}7",       "<Plug>(Marks-next-bookmark7)",   desc = "Moves to the next bookmark of of the same group" },
            { "m{7",       "<Plug>(Marks-prev-bookmark7)",   desc = "Moves to the previous bookmark of of the same group" },
            { "m}8",       "<Plug>(Marks-next-bookmark8)",   desc = "Moves to the next bookmark of of the same group" },
            { "m{8",       "<Plug>(Marks-prev-bookmark8)",   desc = "Moves to the previous bookmark of of the same group" },
            { "m}9",       "<Plug>(Marks-next-bookmark9)",   desc = "Moves to the next bookmark of of the same group" },
            { "m{9",       "<Plug>(Marks-prev-bookmark9)",   desc = "Moves to the previous bookmark of of the same group" },

            -- { "<Plug>(Marks-toggle-bookmark[0-9])", desc = "Toggles a bookmark from group" },
        },
        config = true,
    },
}
