[rocks]

[plugins]
"rocks.nvim" = "2.35.1"
"rocks-git.nvim" = "2.0.0"
"rocks-config.nvim" = "2.1.4"
"rocks-lazy.nvim" = "1.0.0"
"rocks-treesitter.nvim" = "scm"

vim-bbye = { git = "moll/vim-bbye", rev = "v1.0.1" }

# Vim
nvim-surround = "2.1.5"
vim-repeat = { git = "tpope/vim-repeat", rev = "v1.2^{}" }

# Commands / Actions
"gitignore.nvim" = { git = "wintermute-cell/gitignore.nvim", cmd = "Gitignore" }
"treesj" = { git = "wansmer/treesj" }

# +----------------------------------------------------------+
# | Enhancements                                             |
# +----------------------------------------------------------+
# Cursor
"mini.misc" = { rev = "0.9.0" }
# Dial
"dial.nvim" = "0.4.0"
# Fold
"nvim-ufo" = "1.4.0"

# Dependencies
"promise-async" = "scm"

# Unsorted
"hydra.nvim" = "1.0.2"

[config]
plugins_dir = "plugins/misc/"
auto_setup = false

# Left off at lua.quitlox.plugins.editor.actions <- completed, move to enhanced
