[rocks]

[plugins]
"rocks.nvim" = "2.36.1"
"rocks-git.nvim" = "2.0.1"
"rocks-config.nvim" = "2.1.4"
"rocks-lazy.nvim" = "1.0.0"

# +----------------------------------------------------------+
# | Colorschemes                                             |
# +----------------------------------------------------------+
"nvim" = { git = "catppuccin/nvim", rev = "v1.7.0" }
"nvim-web-devicons" = { version = "0.100" }
"tiny-devicons-auto-colors.nvim" = { git = "rachartier/tiny-devicons-auto-colors.nvim" }

# +----------------------------------------------------------+
# | Editor                                                   |
# +----------------------------------------------------------+
# +- Vim Built-in Enhancements ------------------------------+
"dial.nvim" = { git = "monaqa/dial.nvim" }                                # Dial
"mini.misc" = { git = "echasnovski/mini.misc" }                           # Cursor
"vim-matchup" = { git = "andymass/vim-matchup" }                          # Matchup
"nvim-hlslens" = { git = "kevinhwang91/nvim-hlslens" }                    # Search
"highlight-undo.nvim" = { git = "tzachar/highlight-undo.nvim" }           # Undo
"wrapping.nvim" = { git = "andrewferrier/wrapping.nvim", rev = "v1.2.0" } # Wrap
"yanky.nvim" = "scm"

# +- Visual Enhancements ------------------------------------+
"nvim-colorizer.lua" = { git = "NvChad/nvim-colorizer.lua" } # Colorizer
"vim-illuminate" = { git = "rrethy/vim-illuminate" }         # Cursor Word
"indent-blankline.nvim" = "3.7.1"

# +- Vim Motions --------------------------------------------+
"nvim-surround" = "2.1.5"
"flash.nvim" = "2.1.0"
"vim-repeat" = { git = "tpope/vim-repeat", rev = "v1.2^{}" } # Dot Repeat

# +- Miscellenous -------------------------------------------+
"guess-indent.nvim" = { git = "nmac427/guess-indent.nvim" }
"vim-bbye" = { git = "moll/vim-bbye", rev = "v1.0.1" }
"treesj" = { git = "wansmer/treesj" }

# +----------------------------------------------------------+
# | Integrated Development Environment                       |
# +----------------------------------------------------------+

# +- Comments / Documentation -------------------------------+
"neogen" = "2.18.0"
"comment-box.nvim" = "scm"

# +- Completion ---------------------------------------------+
"nvim-cmp" = { git = "hrsh7th/nvim-cmp" }
"cmp-nvim-lsp-signature-help" = { git = "hrsh7th/cmp-nvim-lsp-signature-help" }
"cmp-nvim-lsp" = { git = "hrsh7th/cmp-nvim-lsp" }
"cmp-path" = { git = "hrsh7th/cmp-path" }
"cmp-cmdline" = { git = "hrsh7th/cmp-cmdline" }
"cmp-buffer" = { git = "hrsh7th/cmp-buffer" }
"cmp-rg" = { git = "lukas-reineke/cmp-rg", rev = "v1.3.9" }
"cmp-dap" = { git = "rcarriga/cmp-dap" }
"lspkind.nvim" = { git = "onsails/lspkind-nvim" }
# Copilot
"copilot.vim" = { git = "github/copilot.vim", rev = "v1.38.0" }

# +- Debugging ----------------------------------------------+
"nvim-dap" = "0.8.0"
"nvim-dap-ui" = "4.0.0"
"nvim-dap-virtual-text" = { git = "theHamsta/nvim-dap-virtual-text" }
"goto-breakpoints.nvim" = { git = "ofirgall/goto-breakpoints.nvim" }
"persistent-breakpoints.nvim" = { git = "weissle/persistent-breakpoints.nvim" }
# +- Debugging: Adapters ------------------------------------+
"neotest-python" = { git = "nvim-neotest/neotest-python" }

# +- Git ----------------------------------------------------+
"git-conflict.nvim" = { git = "akinsho/git-conflict.nvim", rev = "v2.0.0" }
"gitsigns.nvim" = { git = "lewis6991/gitsigns.nvim", rev = "v0.9.0" }
"neogit" = "1.0.0"
"diffview.nvim" = "scm"
"octo.nvim" = "scm"
"gitlab.nvim" = { git = "harrisoncramer/gitlab.nvim", rev = "v2.7.1" }

# +- Language Server Protocol -------------------------------+
"clear-action.nvim" = { git = "luckasRanarison/clear-action.nvim", rev = "v0.3.0" }
"glance.nvim" = "scm"
"hover.nvim" = "scm"
"lsp_signature.nvim" = "0.3.1"
"lsplinks.nvim" = { git = "icholy/lsplinks.nvim", rev = "v1.0.0" }
"workspace-diagnostics.nvim" = { git = "artemave/workspace-diagnostics.nvim" }

# +- Test ---------------------------------------------------+
"neotest" = "5.4.0"

# +- Tooling ------------------------------------------------+
"conform.nvim" = "7.0.0"
"nvim-lint" = "scm"

# +- Treesitter ---------------------------------------------+
"rocks-treesitter.nvim" = { version = "1.0.2" }
"nvim-treesitter-legacy-api" = "scm"
# +- Treesitter: Modules ------------------------------------+
"targets.vim" = { git = "wellle/targets.vim", rev = "v0.5.0^{}" }
"rainbow-delimiters.nvim" = "0.4.0"
"nvim-autopairs" = { version = "scm", config = "quitlox.plugins.ide.treesitter.autopairs" }
"nvim-ts-autotag" = { version = "scm", event = "InsertEnter" }
"nvim-ts-context-commentstring" = { version = "scm", config = "quitlox.plugins.ide.treesitter.context-commentstring" }
"nvim-treesitter-endwise" = { git = "RRethy/nvim-treesitter-endwise", event = "InsertEnter", config = "quitlox.plugins.ide.treesitter.endwise" }
"nvim-treesitter-textsubjects" = { git = "RRethy/nvim-treesitter-textsubjects", event = "InsertEnter", config = "quitlox.plugins.ide.treesitter.textsubjects" }
"nvim-treesitter-textobjects" = { version = "scm", event = "InsertEnter", config = "quitlox.plugins.ide.treesitter.textobjects" }
"nvim-various-textobjs" = { version = "scm", event = "InsertEnter", config = "quitlox.plugins.ide.treesitter.textobjects-extra" }
# +- Treesitter: Parsers ------------------------------------+
tree-sitter-html = "0.0.2"
tree-sitter-ecma = "0.0.2"
tree-sitter-lua = "0.0.2"
tree-sitter-jsonc = "0.0.2"
tree-sitter-css = "0.0.2"
tree-sitter-scss = "0.0.2"
tree-sitter-javascript = "0.0.2"
tree-sitter-json = "0.0.2"
tree-sitter-toml = "0.0.2"
tree-sitter-typescript = "0.0.3"
tree-sitter-python = "0.0.2"

# +- Miscellenous -------------------------------------------+
"gitignore.nvim" = { git = "wintermute-cell/gitignore.nvim" }

# +----------------------------------------------------------+
# | Language Support                                         |
# +----------------------------------------------------------+
"nvim-lspconfig" = "0.1.8"
# "tailwind-tools.nvim" = { git = "luckasRanarison/tailwind-tools.nvim", rev = "v0.2.0", config = "quitlox.plugins.lang.tailwind" }
# +- Config -------------------------------------------------+
"schemastore.nvim" = { version = "scm", config = "quitlox.plugins.lang.config-lang" }
# +- HTTP ---------------------------------------------------+
"kulala.nvim" = { git = "mistweaverco/kulala.nvim", rev = "v2.5.1", config = "quitlox.plugins.lang.http" }
# +- Go -----------------------------------------------------+
"go.nvim" = { version = "0.9.0", ft = [ "go", "gomod" ], config = "quitlox.plugins.lang.go" }
"guihua.lua" = { git = "ray-x/guihua.lua", rev = "v0.1^{}", ft = [ "go", "gomod" ] }
# +- LaTeX --------------------------------------------------+
"vimtex" = { git = "lervag/vimtex", rev = "v2.9" }
# +- Lua ----------------------------------------------------+
"lazydev.nvim" = { version = "1.8.0", config = "quitlox.plugins.lang.lua" }
"luvit-meta" = { git = "Bilal2453/luvit-meta" }
# +- Markdown -----------------------------------------------+
"markdown-preview.nvim" = { git = "iamcco/markdown-preview.nvim", rev = "v0.0.9^{}", config = "quitlox.plugins.lang.markdown-preview" }
"markdown.nvim" = { git = "meanderingprogrammer/markdown.nvim", rev = "v4.1.0^{}", config = "quitlox.plugins.lang.markdown-render", ft = "markdown" }
# +- Python -------------------------------------------------+
"nvim-dap-python" = "scm"
"venv-selector.nvim" = { git = "linux-cultist/venv-selector.nvim", branch = "regexp" }
# +- Rust ---------------------------------------------------+
"rustaceanvim" = { version = "4.26.1", config = "quitlox.plugins.lang.rust" }
# +- Typescript ---------------------------------------------+
"typescript-tools.nvim" = { version = "scm", config = "quitlox.plugins.lang.typescript" }
# +- Vim ----------------------------------------------------+
"one-small-step-for-vimkind" = "scm"

# TODO: lang/clangd

# +- Minor Languages ----------------------------------------+
"nvim-ansible" = { git = "mfussenegger/nvim-ansible" }
"vim-sage" = { git = "petRUShka/vim-sage" }
"yuck.vim" = { git = "elkowar/yuck.vim" }

# +----------------------------------------------------------+
# | Components                                               |
# +----------------------------------------------------------+

# +- Breadcrumbs --------------------------------------------+
"barbecue.nvim" = "scm"
"nvim-navic" = "scm"

# +- Bufferline ---------------------------------------------+
"bufferline.nvim" = "4.7.0"

# +- ChatGPT ------------------------------------------------+
"gp.nvim" = { git = "robitx/gp.nvim", rev = "v3.4.0" }

# +- File Explorer ------------------------------------------+
"neo-tree.nvim" = "3.26"
"nvim-window-picker" = { git = "s1n7ax/nvim-window-picker", rev = "v2.0.3" } # neo-tree.nvim
"oil.nvim" = "2.11.0"

# +- Finder -------------------------------------------------+
# Telescope
"telescope.nvim" = "scm"
"telescope-fzf-native.nvim" = { git = "nvim-telescope/telescope-fzf-native.nvim", build = "make" }
"smart-open.nvim" = "scm"
"telescope-helpgrep.nvim" = { git = "catgoose/telescope-helpgrep.nvim" }
# Keymaps
"which-key.nvim" = "3.13.2"
# Commands
"legendary.nvim" = "2.13.11"
# Buffers
"arrow.nvim" = { git = "otavioschwanck/arrow.nvim" }

# +- Notifications ------------------------------------------+
"nvim-notify" = "3.13.5"
"fidget.nvim" = "1.4.1"

# +- REPL ---------------------------------------------------+
"molten-nvim" = {git = "benlubas/molten-nvim", rev = "v1.8.4"}

# +- Runner (Overseer) --------------------------------------+
"overseer.nvim" = "1.4.0"

# +- Statusline (Lualine) -----------------------------------+
"lualine.nvim" = "scm"
"lualine-so-fancy.nvim" = { git = "meuter/lualine-so-fancy.nvim" }
"lualine-pretty-path" = { git = "bwpge/lualine-pretty-path" }

# +- Terminal (toggleterm) ----------------------------------+
"toggleterm.nvim" = "2.12.0"

# +- Quickfix -----------------------------------------------+
"trouble.nvim" = "3.6.0"

# +- Miscelleneous ------------------------------------------+
"edgy.nvim" = "1.10.2"
"dressing.nvim" = "2.2.2"
"icon-picker.nvim" = "scm"
"todo-comments.nvim" = "1.3.0"

# +----------------------------------------------------------+
# | Dependencies                                             |
# +----------------------------------------------------------+
"promise-async" = "scm"
"plenary.nvim" = "scm"
"nui.nvim" = "0.3.0"
"sqlite.lua" = "1.2.2"
"nvim-nio" = "1.10.0"
"fixcursorhold.nvim" = { git = "antoinemadec/FixCursorHold.nvim" } # neotest
"image.nvim" = "1.3.0"

# +----------------------------------------------------------+
# | New and Unsorted                                         |
# +----------------------------------------------------------+
"profile.nvim" = { git = "stevearc/profile.nvim" }
tree-sitter-http = "0.0.1"

# +----------------------------------------------------------+
# | Bundles                                                  |
# +----------------------------------------------------------+

[bundles.editor]
items = [
  "dial.nvim",
  "mini.misc",
  "vim-matchup",
  "highlight-undo.nvim",
  "wrapping.nvim",
  "yanky.nvim",
  "nvim-colorizer.lua",
  "vim-illuminate",
  "indent-blankline.nvim",
  "nvim-surround",
  "flash.nvim",
  "vim-repeat",
  "guess-indent.nvim",
  "vim-bbye",
  "treesj",
]
config = "quitlox.plugins.editor"

# +- Integrated Developer Environment -----------------------+
[bundles.cmp]
items = [
  "nvim-cmp",
  "cmp-nvim-lsp-signature-help",
  "cmp-path",
  "cmp-cmdline",
  "cmp-buffer",
  "cmp-rg",
  "lspkind.nvim",
]
config = "quitlox.plugins.ide.cmp"

[bundles.dap]
items = [
  "nvim-dap-ui",
  "nvim-dap-virtual-text",
  "goto-breakpoints.nvim",
  "persistent-breakpoints.nvim",
  # Adapters
  "neotest-python",
]
config = "quitlox.plugins.ide.dap"

[bundles.lsp]
items = [
  "clear-action.nvim",
  "glance.nvim",
  "hover.nvim",
  "lsp_signature.nvim",
  "lsplinks.nvim",
  "workspace-diagnostics.nvim",
]
config = "quitlox.plugins.ide.lsp"

# +- Language Support ---------------------------------------+
[bundles.python]
items = ["nvim-dap-python", "venv-selector.nvim"]
config = "quitlox.plugins.lang.python"

# +- Components ---------------------------------------------+
[bundles.telescope]
items = [
  "telescope.nvim",
  "telescope-fzf-native.nvim",
  "smart-open.nvim",
  "telescope-helpgrep.nvim",
]
config = "quitlox.plugins.telescope"

# +----------------------------------------------------------+
# | Config                                                   |
# +----------------------------------------------------------+

[config]
plugins_dir = "quitlox/plugins/"
auto_setup = false

# +----------------------------------------------------------+
# | Graveyard                                                |
# +----------------------------------------------------------+
# "marks.nvim" = { git = "chentoast/marks.nvim" }
