---
- name: Install sound base packages
  community.general.pacman:
    name: pipewire lib32-pipewire pipewire-docs wireplumber pipewire-alsa pipewire-pulse pipewire-audio

- name: Install sound front-end packages
  community.general.pacman:
    name: pavucontrol pamixer

- name: Remove pulseaudio
  community.general.pacman:
    name: pulseaudio pulseaudio-bluetooth
    state: absent

- name: Configure noise supression
  ansible.builtin.copy:
    src: "{{ role_path }}/files/99-input-denoising.conf"
    dest: /home/{{ user.name }}/.config/pipewire/pipewire.conf.d/99-input-denoising.conf
    owner: { { user.name } }
    group: { { user.name } }
    mode: 0644
  community.general.pacman: noise-suppression-for-voice
  notify: restart pipewire
