---
- name: Install and Configure VSCode for Debian, Redhat, SUSE
  ansible.builtin.include_role:
    name: library/gantsign.visual-studio-code
  vars:
    visual_studio_code_extensions: "{{ vscode_extensions }}"
  when: ansible_facts['os_family'] != "Archlinux"

- name: Install VSCode
  aur:
    name: visual-studio-code-bin
    user: "{{ user.name }}"
  become: true
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install VSCode extensions
  ansible.builtin.command:
    cmd: "code --install-extension {{ item }} --force"
  loop: "{{ vscode_extensions }}"
  become_user: "{{ user.name }}"
  environment:
    DISPLAY: ":0"
  when: ansible_facts['os_family'] == "Archlinux"

