---
- name: Install mail client
  ansible.builtin.package:
    name: thunderbird
  become: true
- name: Install discord
  ansible.builtin.package:
    name: discord
  become: true
- name: Install browser
  ansible.builtin.package:
    name: firefox
  become: true

- name: Install and configure zathura
  block:
    - name: Install zathura as pdf reader
      community.general.pacman:
        name:
          # Zathura is a highly customizable and functional document viewer.
          - zathura
          # PDF support for Zathura
          - zathura-pdf-mupdf
      become: true

    - name: Set zathura as default pdf reader
      ansible.builtin.ini_file:
        path: "/home/{{ user_name }}/.config/mimeapps.list"
        section: Default Applications
        value: org.pwmt.zathura.desktop
        option: x-scheme-handler/pdf
        owner: "{{ user_name }}"
        group: "{{ user_name }}"

- name: Install obsidian
  ansible.builtin.package:
    name: obsidian
  become: true

- name: Install reference manager
  kewlfft.aur.aur:
    name: zotero-bin
  become: true
  become_user: aur_builder

  # FIXME: Zotero addons

- name: Install LaTeX distribution and dependencies
  block:
    - name: Install TexLive
      community.general.pacman:
        name:
          # A modernized, complete, self-contained TeX/LaTeX engine,
          # powered by XeTeX and TeXLive.
          # > Used by ~/.config/vim/settings/plugins/vimtex.vim
          - texlive-basic
          # > Needed for biblatex files
          - biber
      become: true
    - name: Install dependencies
      # Pretty-Print LaTeX: A tool to reformat the output of latex
      # and friends into readable messages.
      # > Used by ~/.config/vim/settings/plugins/vimtex.vim
      kewlfft.aur.aur:
        name: pplatex-git
      become: true
      become_user: aur_builder
