- name: Playbook for any home computing device
  hosts: localhost
  connection: local
  gather_facts: true

  vars_files:
    - group_vars/all
    - /home/quitlox/.local/share/chezmoi/private_dot_config/ansible/vault.yml

  handlers:
    - include: ../handlers/main.yml

  roles:

    - linux/applications/atuin-client

    - linux/system/user

    - arch/system/beep
    - arch/system/firmware
    - arch/system/hibernate
    - arch/system/laptop
    - arch/system/microcode
    - arch/system/mkinitcpio
    - arch/system/numlock
    - arch/system/pacman
    - arch/system/ssd
    - arch/system/swap
    - arch/system/vm-guest
    - arch/system/yay

    - arch/desktop-xorg/appearance
    - arch/desktop-xorg/brightness
    - arch/desktop-xorg/clipboard
    - arch/desktop-xorg/environment
    - arch/desktop-xorg/fonts
    - arch/desktop-xorg/monitors
    - arch/desktop-xorg/printing
    - arch/desktop-xorg/screenshot
    - arch/desktop-xorg/sound
    - arch/desktop-xorg/wacom

    - linux/applications/cmd
    - linux/applications/desktop
    - linux/applications/dev
    - linux/applications/docker
    - linux/applications/dotfiles
    # - linux/applications/hacking
    - linux/applications/vscode

    - linux/system/bluetooth
    - linux/system/locale
    - linux/system/network
    - linux/system/ssh
    - linux/system/time
    # - linux/system/virtualbox

