---
- name: Validate timezone variable
  assert:
    that:
      - timezone is defined
      - timezone is string
      - "'/' in timezone"
      - timezone.split('/')[0] in valid_regions
      - "timezone in valid_timezones"
    fail_msg: "The timezone '{{ timezone }}' is not valid. Please provide a valid 'Region/City' format that exists on the system."

- name: Symlink /etc/localtime to timezone
  ansible.builtin.file:
    src: "/usr/share/zoneinfo/{{ timezone }}"
    dest: /etc/localtime
    state: link
    force: true
  when: timezone in valid_timezones
