---
- name: Install bluez and bluez-utils packages
  community.general.pacman:
    name:
      - bluez
      - bluez-libs
      - bluez-utils
    state: present
  when:
    - ansible_virtualization_role | lower != "guest"
    - ansible_facts['os_family'] == "Archlinux"

# - name: Load btusb kernel module
#   community.general.modprobe:
#     name: btusb
#     state: present
#   when:
#     - ansible_virtualization_role | lower != "guest"
#     - ansible_facts['os_family'] == "Archlinux"

# - name: Ensure btusb module is loaded at boot
#   ansible.builtin.lineinfile:
#     path: /etc/modules-load.d/btusb.conf
#     line: btusb
#     create: true
#   when:
#     - ansible_virtualization_role | lower != "guest"
#     - ansible_facts['os_family'] == "Archlinux"

- name: Start and enable bluetooth.service
  ansible.builtin.systemd:
    name: bluetooth.service
    state: started
    enabled: true
  when: ansible_virtualization_role | lower != "guest"

- name: Install bluetooth graphical interface
  ansible.builtin.package:
    name: blueman
    state: present
  when:
    - not system.headless
    - ansible_facts['os_family'] == "Archlinux"
