---
- name: Configure mkinitcpio
  ansible.builtin.lineinfile:
    path: /etc/mkinitcpio.conf
    regexp: '^HOOKS=\(.*\)'
    line: "HOOKS=(base udev autodetect keyboard modconf block filesystems resume fsck numlock)"
    state: present
  become: true
  notify: regenerate initramfs
