---
- name: Restart Fail2Ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted
  listen: restart fail2ban

- name: Restart nftables
  ansible.builtin.systemd:
    name: nftables
    state: restarted
  listen: restart nftables

- name: Restart firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: restarted
  listen: restart firewalld
