---
- name: Configure CPU frequency scaling
  block:
    - name: Install cpupower
      community.general.pacman:
        name: cpupower
      become: true
    - name: Set governor to ondemand
      ansible.builtin.lineinfile:
        path: /etc/default/cpupower
        regexp: "^#governor='ondemand'"
        line: "governor='ondemand'"
      become: true
    - name: Enable and start cpupower service
      ansible.builtin.systemd:
        name: cpupower.service
        enabled: true
      become: true

- name: Configure automatic hibernate on low battery
  ansible.builtin.copy:
    src: "{{ role_path }}/files/99-low_battery.rules"
    dest: /etc/udev/rules.d/99-low_battery.rules
    owner: root
    group: root
    mode: "0644"
  become: true
