---
- name: Create default user
  ansible.builtin.user:
    name: "{{ user.name }}"
    password: "{{ user_password | password_hash('sha512') }}"
    shell: /bin/zsh # TODO: Ensure Zsh is installed

    groups: wheel
    append: true

    create_home: true
    update_password: on_create
  when: user.name is defined
