---
- name: Install Rust
  block:
    - name: "Rust: Check if installed"
      ansible.builtin.shell: command -v cargo
      register: cargo_exists
      ignore_errors: true
      check_mode: false
    - name: "Rust: Download Installer"
      when: cargo_exists is failed
      ansible.builtin.get_url:
        url: https://sh.rustup.rs
        dest: /tmp/sh.rustup.rs
        mode: "0755"
        force: "yes"
      tags:
        - rust
    - name: "Rust: Run install script"
      when: cargo_exists is failed
      ansible.builtin.shell: /tmp/sh.rustup.rs -y
      tags:
        - rust
  when: ansible_facts['os_family'] != "Archlinux"

- name: Install atuin
  community.general.pacman:
    name: atuin
  become: true
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install atuin
  ansible.builtin.command: cargo install atuin
  become: true
  become_user: "{{ user.name }}"
  when: ansible_facts['os_family'] != "Archlinux"

- name: Place configuration file
  ansible.builtin.copy:
    src: "{{ role_path }}/files/config.toml"
    dest: "/home/{{ user.name }}/.config/atuin/config.toml"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"

