#!/bin/sh

# The ~/.config/polybar/config is partly managed by Base16 Manager.
# The file contains the markers
# 	# <<<<<<<<<<
# 	# >>>>>>>>>>
# between which Base16 Manager writes in theme.
#
# This script overwrites the ~/.config/polybar/config, removing
# the content in between the markers.
#
# After running `chezmoi apply`, run `base16-universal-manager`.

sed -i -e '/# <<<<<<<<<</,/# >>>>>>>>>>/c\# <<<<<<<<<<\n# >>>>>>>>>>' ~/.config/polybar/config

